import {
  Activity,
  BellDot,
  CheckCircle2,
  CircleDot,
  Database,
  FileText,
  MessageSquare,
  Network,
  ScrollText,
  Search,
  Shield,
  Users,
  X,
} from 'lucide-react';
import AdvancedProjectTimeline from './AdvancedProjectTimeline.jsx';

export default function ProjectTimelineRouteView({ view }) {
  const {
    DEFAULT_CHAT_PROJECT_ID,
    activeProject,
    allowLocalRuntimeFallbackForActiveProject,
    backendStation,
    chatChannels,
    chatMessages,
    chatProofIdsFromAttachment,
    chatProofIdsFromNode,
    confirmManagerFlowNode,
    exitProjectScene,
    focusedTimelineProofIds,
    isManagerDemoProject,
    openProjectChatProof,
    openProjectTimelineProof,
    renderAutonomousActionDecision,
    sceneTransition,
    selectedTimelineEventId,
    setFocusedTimelineProofIds,
    setSelectedTimelineEventId,
    setTimelineScale,
    setTlDragging,
    setTlPan,
    setTlZoom,
    shouldAttemptBackendProjectWrite,
    syncBackendManagerFlowGraph,
    timelineScale,
    timelineViewportRef,
    tlDragStartRef,
    tlDragging,
    tlPan,
    tlZoom,
  } = view;

    const categoryMeta = {
      thinking: { label: 'Thinking', lane: 'Thinking', color: '#b9782b', Icon: Search },
      decision: { label: 'Decision', lane: 'Decisions', color: '#8f1e18', Icon: Shield },
      collaboration: { label: 'Collaboration', lane: 'Collaboration', color: '#59684b', Icon: Users },
      execution: { label: 'Execution', lane: 'Execution', color: '#bcae86', Icon: Activity },
      submission: { label: 'Submission', lane: 'Submissions', color: '#d8c99f', Icon: FileText },
      communication: { label: 'Communication', lane: 'Communication', color: '#7b6542', Icon: MessageSquare },
      monitoring: { label: 'Monitoring', lane: 'Monitoring', color: '#3f5d69', Icon: BellDot },
      evidence: { label: 'Evidence', lane: 'Evidence', color: '#efe2bd', Icon: Database },
    };
    const channelNameById = Object.fromEntries(chatChannels.map(channel => [channel.id, channel.name]));
    const categoryOrder = ['thinking', 'decision', 'collaboration', 'execution', 'submission', 'communication', 'monitoring', 'evidence'];
    const edgeMeta = {
      leader_assignment: { label: 'Leader assignment', color: '#8f1e18' },
      agent_collaboration: { label: 'Agent collaboration', color: '#59684b' },
      task_dependency: { label: 'Task dependency', color: '#bcae86' },
      change_impact: { label: 'Change impact', color: '#b9782b' },
      reporting: { label: 'Report line', color: '#d8c99f' },
      evidence: { label: 'Evidence line', color: '#7b6542' },
    };
    const importanceRank = { minor: 0, normal: 1, major: 2, critical: 3 };
    const localAttachmentTypeFor = (node) => {
      const text = `${node.category || ''} ${node.subtype || ''} ${node.source || ''}`.toLowerCase();
      if (/meeting/.test(text)) return 'meeting-minutes';
      if (/report|summary|submission/.test(text)) return 'report';
      if (/test/.test(text)) return 'test-result';
      if (/heartbeat|monitor|loop/.test(text)) return 'runtime-check';
      if (/message|chat|communication/.test(text)) return 'chat-record';
      if (/evidence|proof/.test(text)) return 'evidence-packet';
      return 'workflow-attachment';
    };
    const localSubmissionIntentFor = (node) => {
      const text = `${node.category || ''} ${node.subtype || ''}`.toLowerCase();
      if (/meeting/.test(text)) return 'Submit meeting minutes and attendance evidence.';
      if (/report|summary|submission/.test(text)) return 'Submit a deliverable report for manager/user review.';
      if (/heartbeat|monitor|loop/.test(text)) return 'Submit an Agent runtime check-in.';
      if (/message|chat|communication/.test(text)) return 'Submit a communication record with receipt context.';
      return 'Submit an Agent-authored workflow commit for manager review.';
    };
    const withLocalSubmissionArtifacts = (node) => {
      const attachment = {
        id: `${node.id}_attachment_main`,
        type: localAttachmentTypeFor(node),
        title: `${node.title} attachment`,
        summary: node.summary,
        source: node.source,
        autoGenerated: true,
        proofIds: node.proofIds || [],
        timelineLogIds: node.timelineLogIds || [],
        eventIds: node.eventIds || [],
        taskId: node.taskId || null,
        route: node.route || null,
      };
      const field = (id, label, source, value, required = true) => ({
        id,
        label,
        source,
        required,
        status: required && (value === null || value === undefined || value === '' || (Array.isArray(value) && !value.length)) ? 'missing' : 'filled',
      });
      return {
        ...node,
        commitMessage: node.commitMessage || node.summary || node.title,
        committerIds: node.committerIds || [node.agentId].filter(Boolean),
        attachments: node.attachments?.length ? node.attachments : [attachment],
        submission: node.submission || {
          id: `submission_${node.id}`,
          generatedBy: 'manager-flow-fallback-protocol',
          intent: localSubmissionIntentFor(node),
          commitMessage: node.commitMessage || node.summary || node.title,
          submittedByAgentId: node.agentId || null,
          submittedByAgentName: node.agentName || 'Project',
          committerIds: node.committerIds || [node.agentId].filter(Boolean),
          coAuthorIds: node.coAuthorIds || [],
          participantIds: node.participantIds || node.affectedAgentIds || [],
          attachmentIds: [attachment.id],
          requiredFields: [
            field('category', 'Category', 'agent', node.category),
            field('subtype', 'Subtype', 'agent', node.subtype),
            field('commitMessage', 'Commit message', 'agent', node.commitMessage || node.summary || node.title),
            field('submitter', 'Submitting Agent', 'agent', node.agentId || node.agentName),
            field('attachments', 'Submitted artifact attachment', 'agent', [attachment]),
          ],
          autoFields: [
            field('id', 'Node ID', 'system', node.id, false),
            field('time', 'Commit time', 'system', node.time, false),
            field('status', 'Workflow status', 'system', node.status, false),
            field('source', 'Source ledger', 'system', node.source, false),
          ],
        },
      };
    };
    const activeFlowGraphProjectId = String(activeProject.id || '').toLowerCase();
    const backendFlowGraphFromStation = String(backendStation.managerFlowGraph?.projectId || '').toLowerCase() === activeFlowGraphProjectId
      ? backendStation.managerFlowGraph
      : null;
    const backendReadyPackageForFlowGraph = String(backendStation.managerReadyPackage?.projectId || '').toLowerCase() === activeFlowGraphProjectId
      ? backendStation.managerReadyPackage
      : null;
    const backendFlowGraph = backendFlowGraphFromStation || backendReadyPackageForFlowGraph?.managerFlowGraph || null;
    const backendDashboardForFlowGraph = String(backendStation.managerDashboard?.projectId || '').toLowerCase() === activeFlowGraphProjectId
      ? backendStation.managerDashboard
      : null;
    const backendProofMapFromStationForFlowGraph = String(backendStation.readinessProofMap?.projectId || '').toLowerCase() === activeFlowGraphProjectId
      ? backendStation.readinessProofMap
      : null;
    const backendReadinessProofMapForFlowGraph = backendProofMapFromStationForFlowGraph
      || backendDashboardForFlowGraph?.readinessProofMap
      || backendReadyPackageForFlowGraph?.managerDashboard?.readinessProofMap
      || backendReadyPackageForFlowGraph?.readinessProofMap
      || null;
    const backendTimelineProofMap = backendReadinessProofMapForFlowGraph || null;
    const buildFallbackFlowGraph = () => {
      const agentStatusNodes = activeProject.team.map((agent, index) => {
        const state = activeProject.agentStates?.[agent.id] || {};
        return {
          id: `agent-status-${agent.id}`,
          category: 'monitoring',
          subtype: 'agent-heartbeat',
          title: `${agent.name} current state`,
          agentId: agent.id,
          agentName: agent.name,
          taskId: null,
          time: state.lastActiveAt || activeProject.updatedAt || activeProject.createdAt || new Date().toISOString(),
          summary: state.currentPlan?.focus || state.status || 'Waiting for backend graph sync.',
          status: state.status === 'blocked' ? 'blocked' : 'published',
          importance: index === 0 ? 'major' : 'normal',
          source: 'agentStates',
          proofIds: [],
          relatedNodeIds: [],
          timelineLogIds: [],
          eventIds: [],
        };
      });
      const logNodes = (activeProject.logs || []).slice(0, 24).map((log, index) => {
        const agent = activeProject.team.find(member => member.id === log.agentId || member.name === log.agent);
        const category = /confirmed|approved|decision/i.test(log.eventType || '')
          ? 'decision'
          : /report|completed|test/i.test(log.eventType || '')
            ? 'submission'
            : /management|worker|scheduler/i.test(log.eventType || '')
              ? 'monitoring'
              : 'execution';
        return {
          id: `timeline-log-${log.id || index}`,
          category,
          subtype: log.eventType || 'timeline-log',
          title: log.agent || log.actor || log.eventType || 'Timeline log',
          agentId: log.agentId || agent?.id || null,
          agentName: agent?.name || log.agent || 'Runtime',
          taskId: log.taskId || null,
          time: log.time || activeProject.updatedAt || activeProject.createdAt || new Date().toISOString(),
          summary: log.log || log.text || 'Timeline log',
          status: /blocked/i.test(log.eventType || '') ? 'blocked' : 'published',
          importance: index < 6 ? 'major' : 'normal',
          source: 'timeline logs',
          sourceChannelId: log.sourceChannelId || null,
          receiptCount: log.receiptCount || 0,
          directTargetIds: log.directTargetIds || [],
          proofIds: [String(log.id || '').startsWith('log_') ? String(log.id).slice(4) : null].filter(Boolean),
          timelineLogIds: [log.id].filter(Boolean),
          eventIds: [],
          relatedNodeIds: log.agentId ? [`agent-status-${log.agentId}`] : [],
          attachments: log.attachments || [],
        };
      });
      const nodes = [...agentStatusNodes, ...logNodes].map((node, index) => ({
        ...node,
        sequence: index + 1,
        categoryLabel: categoryMeta[node.category]?.label || node.category,
        hasProof: Boolean(node.proofIds?.length || node.timelineLogIds?.length || node.eventIds?.length),
      })).map(withLocalSubmissionArtifacts);
      const edges = logNodes
        .filter(node => node.agentId)
        .map(node => ({
          id: `fallback-edge-${node.id}`,
          type: node.category === 'submission' ? 'reporting' : 'task_dependency',
          typeLabel: node.category === 'submission' ? 'Report line' : 'Task dependency line',
          fromNodeId: `agent-status-${node.agentId}`,
          toNodeId: node.id,
          label: node.category === 'submission' ? 'Agent report' : 'Agent progress',
          status: 'published',
          importance: node.importance,
          source: node.source,
          proofIds: node.proofIds || [],
          timelineLogIds: node.timelineLogIds || [],
          eventIds: [],
        }));
      const byCategory = nodes.reduce((acc, node) => ({ ...acc, [node.category]: (acc[node.category] || 0) + 1 }), {});
      return {
        projectId: activeProject.id,
        schemaVersion: 'manager-flow-graph/fallback',
        generatedAt: new Date().toISOString(),
        categories: categoryOrder.map(id => ({ id, ...categoryMeta[id], count: byCategory[id] || 0 })),
        summary: {
          nodeCount: nodes.length,
          edgeCount: edges.length,
          proofedNodeCount: nodes.filter(node => node.hasProof).length,
          confirmedNodeCount: nodes.filter(node => node.status === 'confirmed').length,
          blockedNodeCount: nodes.filter(node => node.status === 'blocked').length,
          majorVisibleCount: nodes.filter(node => ['major', 'critical'].includes(node.importance)).length,
          byCategory,
        },
        zoomRules: {
          compact: { label: 'Major and critical only', importances: ['major', 'critical'] },
          medium: { label: 'Agent working path' },
          expanded: { label: 'Chat, report, evidence, and detail' },
        },
        dataSources: {
          eventLedger: activeProject.eventLedger?.length || 0,
          timelineLogs: activeProject.logs?.length || 0,
          messages: chatMessages.filter(message => (message.projectId || DEFAULT_CHAT_PROJECT_ID) === activeProject.id).length,
          tasks: activeProject.tasks?.length || 0,
          agentStates: Object.keys(activeProject.agentStates || {}).length,
          kickoffCharter: Boolean(activeProject.kickoffCharter),
          changeLedger: activeProject.changeLedger?.length || 0,
          managerDashboard: Boolean(backendDashboardForFlowGraph),
        },
        nodes,
        edges,
      };
    };
    const backendOnline = backendStation.connectionStatus === 'online';
    const backendCommandAvailable = shouldAttemptBackendProjectWrite(activeProject);
    const allowFlowFrontendFallbacks = allowLocalRuntimeFallbackForActiveProject(activeProject);
    const backendFlowGraphReady = Boolean(backendFlowGraph?.nodes?.length);
    const missingBackendFlowGraph = {
      projectId: activeProject.id,
      schemaVersion: 'manager-flow-graph/missing-backend',
      generatedAt: new Date().toISOString(),
      dataSource: 'backend-required',
      status: 'backend-model-missing',
      frontendMockSuppressed: true,
      frontendFallbackMode: 'backend-required',
      categories: categoryOrder.map(id => ({ id, ...categoryMeta[id], count: 0 })),
      summary: {
        nodeCount: 0,
        edgeCount: 0,
        proofedNodeCount: 0,
        confirmedNodeCount: 0,
        blockedNodeCount: 0,
        majorVisibleCount: 0,
        byCategory: {},
      },
      zoomRules: {
        compact: { label: 'Major and critical only', importances: ['major', 'critical'] },
        medium: { label: 'Agent working path' },
        expanded: { label: 'Chat, report, evidence, and detail' },
      },
      dataSources: {
        managerFlowGraphRoute: `/projects/${activeProject.id}/manager-flow-graph`,
        managerReadyPackage: Boolean(backendReadyPackageForFlowGraph),
        managerDashboard: Boolean(backendDashboardForFlowGraph),
      },
      nodes: [],
      edges: [],
    };
    const managerFlowGraph = backendFlowGraphReady
      ? { ...backendFlowGraph, dataSource: backendFlowGraph.dataSource || 'backend-backed' }
      : allowFlowFrontendFallbacks
        ? {
            ...buildFallbackFlowGraph(),
            dataSource: 'frontend-fallback',
            frontendFallbackMode: 'demo-or-offline',
            demoOnly: isManagerDemoProject(activeProject),
          }
        : missingBackendFlowGraph;
    const managerFlowGraphSourceLabel = managerFlowGraph.frontendMockSuppressed
      ? 'backend model missing'
      : managerFlowGraph.dataSource === 'frontend-fallback'
        ? 'demo data'
        : 'backend-backed';
    const scaleProfiles = {
      month: { label: 'Major', test: node => ['major', 'critical'].includes(node.importance) },
      week: { label: 'Path', test: node => ['major', 'critical'].includes(node.importance) || ['decision', 'collaboration', 'execution', 'submission', 'monitoring'].includes(node.category) },
      day: { label: 'Work', test: node => node.category !== 'evidence' || ['major', 'critical'].includes(node.importance) },
      hour: { label: 'Detail', test: () => true },
    };
    const scaleOrder = ['month', 'week', 'day', 'hour'];
    const zoomDetail = tlZoom < 0.72 ? 'compact' : tlZoom < 1.12 ? 'medium' : 'expanded';
    const zoomScale = tlZoom < 0.72 ? 'month' : tlZoom < 1.04 ? 'week' : tlZoom < 1.42 ? 'day' : 'hour';
    const activeScaleProfile = scaleProfiles[zoomScale] || scaleProfiles.day;
    const visibleNodes = Array.from(new Map((managerFlowGraph.nodes || [])
      .filter(activeScaleProfile.test)
      .filter(node => zoomDetail !== 'compact' || ['major', 'critical'].includes(node.importance))
      .map(node => [node.id, node])).values())
      .sort((a, b) => {
        const areaA = a.commitArea?.index ?? managerFlowGraph.layout?.nodeLayoutHints?.[a.id]?.index;
        const areaB = b.commitArea?.index ?? managerFlowGraph.layout?.nodeLayoutHints?.[b.id]?.index;
        if (Number.isFinite(areaA) && Number.isFinite(areaB) && areaA !== areaB) return areaA - areaB;
        const timeA = Date.parse(a.time) || 0;
        const timeB = Date.parse(b.time) || 0;
        if (timeA !== timeB) return timeA - timeB;
        const branchA = a.commitArea?.branchIndex ?? managerFlowGraph.layout?.nodeLayoutHints?.[a.id]?.branchIndex;
        const branchB = b.commitArea?.branchIndex ?? managerFlowGraph.layout?.nodeLayoutHints?.[b.id]?.branchIndex;
        if (Number.isFinite(branchA) && Number.isFinite(branchB) && branchA !== branchB) return branchA - branchB;
        return (a.sequence || 0) - (b.sequence || 0);
      });
    const visibleNodeIds = new Set(visibleNodes.map(node => node.id));
    const visibleEdges = (managerFlowGraph.edges || []).filter(edge => visibleNodeIds.has(edge.fromNodeId) && visibleNodeIds.has(edge.toNodeId));
    const nodeMap = Object.fromEntries((managerFlowGraph.nodes || []).map(node => [node.id, node]));
    const selectedNode = visibleNodes.find(node => node.id === selectedTimelineEventId)
      || visibleNodes.find(node => [node.id, ...(node.proofIds || []), ...(node.timelineLogIds || []), ...(node.eventIds || [])].includes(selectedTimelineEventId))
      || null;
    const selectedThinkingFrame = selectedNode?.thinkingFrame || selectedNode?.submission?.thinkingFrame || null;
    const relatedEdges = selectedNode
      ? visibleEdges.filter(edge => edge.fromNodeId === selectedNode.id || edge.toNodeId === selectedNode.id)
      : [];
    const relatedNodeIds = selectedNode
      ? Array.from(new Set(relatedEdges.flatMap(edge => [edge.fromNodeId, edge.toNodeId]).filter(id => id !== selectedNode.id)))
      : [];
    const isProofFocused = (node) => focusedTimelineProofIds.some(id => (
      node.id === id
      || (node.proofIds || []).includes(id)
      || (node.timelineLogIds || []).includes(id)
      || (node.eventIds || []).includes(id)
    ));
    const visibleTimelineProofCount = visibleNodes.filter(isProofFocused).length;
    const uniqueIds = (values) => Array.from(new Set((values || []).filter(Boolean).map(value => String(value))));
    const agentById = new Map((activeProject.team || []).map(agent => [agent.id, agent]));
    const agentDisplay = (agentId) => {
      const agent = agentById.get(agentId);
      return {
        id: agentId || 'project',
        name: agent?.name || agentId || 'Project',
        role: agent?.title || agent?.role || agent?.duty || (agentId ? 'Agent' : 'Project'),
        accent: agent?.color || '#bcae86',
      };
    };
    const nodeCommitters = (node) => uniqueIds([
      ...(node.committerIds || []),
      node.agentId,
      ...(node.coAuthorIds || []),
    ]).map(agentDisplay);
    const committersLabel = (node) => {
      const committers = nodeCommitters(node);
      if (!committers.length) return node.agentName || 'Project';
      if (committers.length === 1) return committers[0].name;
      return `${committers.slice(0, 2).map(person => person.name).join(' + ')}${committers.length > 2 ? ` +${committers.length - 2}` : ''}`;
    };
    const compactText = (value, max = 96) => {
      const text = String(value || '').replace(/\s+/g, ' ').trim();
      if (text.length <= max) return text;
      return `${text.slice(0, Math.max(0, max - 3)).trim()}...`;
    };
    const timeKeyForNode = (node) => {
      if (node.commitArea?.key) return node.commitArea.key;
      const hintKey = managerFlowGraph.layout?.nodeLayoutHints?.[node.id]?.key;
      if (hintKey) return hintKey;
      const parsed = Date.parse(node.time);
      if (Number.isFinite(parsed)) {
        const date = new Date(parsed);
        date.setSeconds(0, 0);
        return date.toISOString();
      }
      return String(node.time || `sequence-${node.sequence || node.id}`).trim();
    };
    const groupedByTime = visibleNodes.reduce((acc, node) => {
      const key = timeKeyForNode(node);
      if (!acc.has(key)) acc.set(key, []);
      acc.get(key).push(node);
      return acc;
    }, new Map());
    const timeColumns = [...groupedByTime.entries()]
      .map(([key, nodes]) => ({
        key,
        time: nodes[0]?.time,
        nodes: nodes.sort((a, b) => {
          const branchA = a.commitArea?.branchIndex ?? managerFlowGraph.layout?.nodeLayoutHints?.[a.id]?.branchIndex;
          const branchB = b.commitArea?.branchIndex ?? managerFlowGraph.layout?.nodeLayoutHints?.[b.id]?.branchIndex;
          if (Number.isFinite(branchA) && Number.isFinite(branchB) && branchA !== branchB) return branchA - branchB;
          return (importanceRank[b.importance] || 0) - (importanceRank[a.importance] || 0) || (a.sequence || 0) - (b.sequence || 0);
        }),
        layoutIndex: Math.min(...nodes.map(node => node.commitArea?.index ?? managerFlowGraph.layout?.nodeLayoutHints?.[node.id]?.index ?? Number.MAX_SAFE_INTEGER)),
      }))
      .sort((a, b) => {
        if (Number.isFinite(a.layoutIndex) && Number.isFinite(b.layoutIndex) && a.layoutIndex !== b.layoutIndex) return a.layoutIndex - b.layoutIndex;
        const timeA = Date.parse(a.time) || 0;
        const timeB = Date.parse(b.time) || 0;
        if (timeA !== timeB) return timeA - timeB;
        return (a.nodes[0]?.sequence || 0) - (b.nodes[0]?.sequence || 0);
      });
    const nodeWidth = zoomDetail === 'expanded' ? 292 : zoomDetail === 'medium' ? 260 : 224;
    const nodeHeight = zoomDetail === 'expanded' ? 144 : zoomDetail === 'medium' ? 126 : 108;
    const branchXGap = nodeWidth + (zoomDetail === 'compact' ? 28 : 38);
    const timeColumnGap = zoomDetail === 'expanded' ? 128 : zoomDetail === 'medium' ? 112 : 92;
    const branchYOffset = zoomDetail === 'expanded' ? 88 : zoomDetail === 'medium' ? 78 : 68;
    const xOffset = 300;
    const maxBranchCount = Math.max(1, ...timeColumns.map(column => column.nodes.length));
    const maxBranchLevel = Math.max(1, Math.ceil((maxBranchCount - 1) / 2));
    const timeAxisY = Math.max(280, 132 + maxBranchLevel * branchYOffset + nodeHeight / 2);
    const branchSlotFor = (index) => {
      if (index === 0) return 0;
      const level = Math.ceil(index / 2);
      return index % 2 === 1 ? -level : level;
    };
    let columnCursor = xOffset;
    const timeColumnLayouts = timeColumns.map((column) => {
      const branchCount = Math.max(1, column.nodes.length);
      const width = Math.max(nodeWidth, (branchCount - 1) * branchXGap + nodeWidth);
      const layout = {
        ...column,
        x: columnCursor,
        width,
        centerX: columnCursor + width / 2,
      };
      columnCursor += width + timeColumnGap;
      return layout;
    });
    const nodeLayout = {};
    timeColumnLayouts.forEach((column, columnIndex) => {
      column.nodes.forEach((node, branchIndex) => {
        const slot = branchSlotFor(branchIndex);
        nodeLayout[node.id] = {
          x: column.x + branchIndex * branchXGap,
          y: timeAxisY + slot * branchYOffset - nodeHeight / 2,
          branchIndex,
          branchCount: column.nodes.length,
          timeColumnIndex: columnIndex,
          w: nodeWidth,
          h: nodeHeight,
        };
      });
    });
    const visibleNodesByPosition = visibleNodes
      .map(node => ({ node, box: nodeLayout[node.id] }))
      .filter(item => item.box)
      .sort((a, b) => a.box.x - b.box.x || a.box.y - b.box.y)
      .map(item => item.node);
    const initialGraphNode = selectedNode || visibleNodesByPosition[0] || null;
    const initialGraphNodeBox = initialGraphNode ? nodeLayout[initialGraphNode.id] : null;
    const defaultGraphPan = initialGraphNodeBox
      ? { x: 300 - initialGraphNodeBox.x, y: 180 - initialGraphNodeBox.y }
      : { x: 0, y: 0 };
    const canvasW = Math.max(1280, columnCursor + 180);
    const canvasH = Math.max(760, timeAxisY + maxBranchLevel * branchYOffset + nodeHeight / 2 + 180);
    const tickEvery = zoomDetail === 'expanded' ? 1 : zoomDetail === 'medium' ? 2 : 3;
    const timeTicks = timeColumnLayouts
      .map((column, index) => ({
        key: `${column.key}-${index}`,
        time: column.time,
        x: column.centerX,
        count: column.nodes.length,
        show: index === 0 || index === timeColumns.length - 1 || index % tickEvery === 0,
      }))
      .filter(tick => tick.show);
    const branchGuides = timeColumnLayouts.filter(column => column.nodes.length > 1).map((column) => {
      const boxes = column.nodes.map(node => nodeLayout[node.id]).filter(Boolean);
      return {
        key: column.key,
        x: column.centerX,
        y: timeAxisY,
        left: Math.min(...boxes.map(box => box.x + box.w / 2)),
        right: Math.max(...boxes.map(box => box.x + box.w / 2)),
        count: column.nodes.length,
      };
    });
    const getAnchor = (edge) => {
      const from = nodeLayout[edge.fromNodeId];
      const to = nodeLayout[edge.toNodeId];
      if (!from || !to) return null;
      const sx = from.x + from.w / 2;
      const sy = from.y + from.h / 2;
      const ex = to.x + to.w / 2;
      const ey = to.y + to.h / 2;
      const bend = Math.max(70, Math.abs(ex - sx) / 2);
      return { sx, sy, ex, ey, path: `M ${sx} ${sy} C ${sx + bend} ${sy}, ${ex - bend} ${ey}, ${ex} ${ey}` };
    };
    const handleGraphWheel = (event) => {
      event.preventDefault();
      if (event.altKey) {
        const current = scaleOrder.indexOf(timelineScale);
        const next = event.deltaY > 0 ? Math.max(0, current - 1) : Math.min(scaleOrder.length - 1, current + 1);
        setTimelineScale(scaleOrder[next]);
        return;
      }
      if (event.shiftKey) {
        setTlPan(prev => ({ ...prev, x: prev.x - event.deltaY }));
        return;
      }
      const rect = event.currentTarget.getBoundingClientRect();
      const pointerX = event.clientX - rect.left;
      const pointerY = event.clientY - rect.top;
      const nextZoom = Math.min(2.2, Math.max(0.52, tlZoom * Math.exp(-event.deltaY * 0.0012)));
      const worldX = (pointerX - tlPan.x) / tlZoom;
      const worldY = (pointerY - tlPan.y) / tlZoom;
      setTlZoom(nextZoom);
      setTlPan({
        x: pointerX - worldX * nextZoom,
        y: pointerY - worldY * nextZoom,
      });
    };
    const handleGraphMouseDown = (event) => {
      if (event.target.closest('button')) return;
      setTlDragging(true);
      tlDragStartRef.current = { x: event.clientX, y: event.clientY, panX: tlPan.x, panY: tlPan.y };
    };
    const handleGraphMouseMove = (event) => {
      if (!tlDragging) return;
      setTlPan({
        x: tlDragStartRef.current.panX + event.clientX - tlDragStartRef.current.x,
        y: tlDragStartRef.current.panY + event.clientY - tlDragStartRef.current.y,
      });
    };
    const resetGraphView = () => {
      setTlPan({ x: 0, y: 0 });
      setTlZoom(1);
      setTimelineScale('day');
      setSelectedTimelineEventId(null);
    };
    const graphTime = (value) => {
      if (!value) return 'No time';
      const clockOnly = String(value).trim().match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);
      if (clockOnly) {
        const hour = String(Math.min(23, Number(clockOnly[1]))).padStart(2, '0');
        return `${hour}:${clockOnly[2]}`;
      }
      const parsed = new Date(value);
      if (Number.isNaN(parsed.getTime())) return String(value);
      const date = parsed.toLocaleDateString(undefined, { year: 'numeric', month: '2-digit', day: '2-digit' });
      const time = parsed.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', hour12: false });
      return `${date} ${time}`;
    };
    const selectedChatProofIds = selectedNode ? chatProofIdsFromNode(selectedNode) : [];
    const selectedProofRouteCandidates = selectedNode ? [
      selectedNode.route,
      selectedNode.proofRoute,
      selectedNode.apiPath,
      selectedNode.backendRoutes?.runtimeAutonomyStatus,
      selectedNode.id === 'runtime-autonomy-status' || selectedNode.source === 'runtimeAutonomyStatus'
        ? `/projects/${activeProject.id}/runtime-autonomy-status`
        : null,
      selectedNode.submission?.route,
      selectedNode.submission?.proofRoute,
      selectedNode.submission?.apiPath,
      ...(selectedNode.attachments || []).map(attachment => attachment.route),
    ].filter(Boolean).map(value => String(value)) : [];
    const selectedNodeRawProofRoute = selectedProofRouteCandidates.find(route => route.startsWith('/projects/'))
      || selectedProofRouteCandidates[0]
      || null;
    const routeCollection = (key) => (backendTimelineProofMap?.[key] || []).map(route => ({ ...route, proofMapKey: key }));
    const selectedNodeProofMapRoutes = (selectedNode ? [
      ...routeCollection('submissionRoutes'),
      ...routeCollection('revisionRoutes'),
      ...routeCollection('evidenceSearchRoutes'),
      ...routeCollection('submissionReviewRoutes'),
      ...routeCollection('sourceReviewRoutes'),
      ...routeCollection('evidenceSourceReviewRoutes'),
      ...routeCollection('brainstormLayerRoutes'),
      ...routeCollection('artifactQualityRoutes'),
      ...routeCollection('evidenceQualityRoutes'),
      ...routeCollection('submissionReviewWorkflowRoutes'),
      ...routeCollection('productTeamDeliveryTraceRoutes'),
      ...routeCollection('productTeamAcceptanceChainRoutes'),
      ...routeCollection('productTeamMissionRunRoutes'),
      ...routeCollection('runtimeAutonomyStatusRoutes'),
      ...(backendTimelineProofMap?.routes || []).map(route => ({ ...route, proofMapKey: 'routes' })),
    ] : []).filter(route => {
      const apiPath = route.apiPath || route.route || route.proofRoute;
      if (selectedNodeRawProofRoute && apiPath === selectedNodeRawProofRoute) return true;
      const proofOverlap = (route.proofIds || []).some(id => selectedChatProofIds.includes(id) || (selectedNode.proofIds || []).includes(id));
      const timelineOverlap = (route.timelineLogIds || []).some(id => (selectedNode.timelineLogIds || []).includes(id));
      const eventOverlap = (route.eventIds || []).some(id => (selectedNode.eventIds || []).includes(id));
      return proofOverlap || timelineOverlap || eventOverlap;
    });
    const selectedNodeExactProofMapRoute = selectedNodeRawProofRoute
      ? selectedNodeProofMapRoutes.find(route => (route.apiPath || route.route || route.proofRoute) === selectedNodeRawProofRoute)
      : null;
    const selectedNodeProofMapRoute = selectedNodeExactProofMapRoute || selectedNodeProofMapRoutes[0] || null;
    const selectedNodeProofRoute = selectedNodeRawProofRoute
      || selectedNodeProofMapRoute?.apiPath
      || selectedNodeProofMapRoute?.route
      || selectedNodeProofMapRoute?.proofRoute
      || null;
    const selectedNodeProofMapKey = selectedNodeProofMapRoute?.proofMapKey || (selectedNodeProofRoute ? 'flow-node-route' : 'not-linked');
    const selectedNodeSubmissionRouteCandidates = selectedNode ? [
      selectedNode.submission?.route,
      selectedNode.submission?.proofRoute,
      selectedNode.submission?.apiPath,
      selectedNode.submissionRoute,
      selectedNode.route,
      selectedNode.proofRoute,
      selectedNode.apiPath,
      ...(selectedNode.attachments || []).map(attachment => attachment.submissionRoute || attachment.route),
    ].filter(Boolean).map(value => String(value)).filter(route => route.includes('/submissions/')) : [];
    const selectedNodeSubmissionRoute = selectedNodeSubmissionRouteCandidates[0] || null;
    const selectedNodeSubmissionId = selectedNode
      ? (
          selectedNode.submission?.id
          || selectedNode.submissionId
          || selectedNode.resourceId
          || selectedNodeSubmissionRoute?.split('/submissions/')[1]?.split(/[?#/]/)[0]
          || (String(selectedNode.id || '').startsWith('agent-submission-') ? String(selectedNode.id).replace(/^agent-submission-/, '') : null)
        )
      : null;
    const selectedNodeHasSubmissionRecord = Boolean(selectedNodeSubmissionRoute || selectedNodeSubmissionId);
    const openSelectedNodeProofMapRoute = () => {
      exitProjectScene();
      window.setTimeout(() => {
        document.querySelector('[data-testid="manager-proof-map"]')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 540);
    };
    const openSelectedNodeSubmissionRecord = () => {
      if (!selectedNodeHasSubmissionRecord) return;
      exitProjectScene();
      const targetTestId = selectedNodeSubmissionId ? `backend-manager-submission-row-${selectedNodeSubmissionId}` : null;
      window.setTimeout(() => {
        const exactTarget = targetTestId
          ? Array.from(document.querySelectorAll('[data-testid]')).find(element => element.getAttribute('data-testid') === targetTestId)
          : null;
        const fallbackTarget = document.querySelector('[data-testid="backend-manager-submissions-snapshot"]');
        (exactTarget || fallbackTarget)?.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }, 540);
    };
    const connectedPeople = selectedNode
      ? uniqueIds([
        ...(selectedNode.committerIds || []),
        selectedNode.agentId,
        ...(selectedNode.coAuthorIds || []),
        ...(selectedNode.participantIds || []),
        ...(selectedNode.affectedAgentIds || []),
        ...relatedNodeIds.map(id => nodeMap[id]?.agentId),
      ]).map(agentId => {
        const person = agentDisplay(agentId);
        const relationshipRoles = selectedNode.relationshipRoles || {};
        const role = relationshipRoles[agentId]
          || ((selectedNode.committerIds || []).includes(agentId) || selectedNode.agentId === agentId ? 'primary-committer' : null)
          || ((selectedNode.coAuthorIds || []).includes(agentId) ? 'co-committer' : null)
          || ((selectedNode.participantIds || []).includes(agentId) ? 'participant' : null)
          || ((selectedNode.affectedAgentIds || []).includes(agentId) ? 'impacted' : 'related');
        return { ...person, relation: role };
      })
      : [];
    const relationshipGraph = (() => {
      const width = 370;
      const height = 250;
      const center = { x: width / 2, y: height / 2 };
      const radiusX = 138;
      const radiusY = 84;
      const people = connectedPeople.map((person, index) => {
        const angle = connectedPeople.length === 1 ? -Math.PI / 2 : (-Math.PI / 2) + (index * Math.PI * 2) / connectedPeople.length;
        return {
          ...person,
          x: center.x + Math.cos(angle) * radiusX,
          y: center.y + Math.sin(angle) * radiusY,
        };
      });
      return { width, height, center, people };
    })();

    return (
      <AdvancedProjectTimeline
          view={{
            CheckCircle2,
            CircleDot,
            Database,
            FileText,
            MessageSquare,
            Network,
            ScrollText,
            X,
            activeProject,
            agentDisplay,
            backendCommandAvailable,
            backendStation,
            branchGuides,
            canvasH,
            canvasW,
            categoryMeta,
            categoryOrder,
            channelNameById,
            chatProofIdsFromAttachment,
            committersLabel,
            compactText,
            confirmManagerFlowNode,
            connectedPeople,
            defaultGraphPan,
            edgeMeta,
            exitProjectScene,
            focusedTimelineProofIds,
            getAnchor,
            graphTime,
            handleGraphMouseDown,
            handleGraphMouseMove,
            handleGraphWheel,
            isProofFocused,
            managerFlowGraph,
            managerFlowGraphSourceLabel,
            nodeCommitters,
            nodeLayout,
            nodeMap,
            openProjectChatProof,
            openProjectTimelineProof,
            openSelectedNodeProofMapRoute,
            openSelectedNodeSubmissionRecord,
            relatedEdges,
            relatedNodeIds,
            relationshipGraph,
            renderAutonomousActionDecision,
            resetGraphView,
            scaleProfiles,
            sceneTransition,
            selectedChatProofIds,
            selectedNode,
            selectedNodeHasSubmissionRecord,
            selectedNodeProofMapKey,
            selectedNodeProofMapRoutes,
            selectedNodeProofRoute,
            selectedNodeSubmissionId,
            selectedNodeSubmissionRoute,
            selectedThinkingFrame,
            setFocusedTimelineProofIds,
            setSelectedTimelineEventId,
            setTlDragging,
            setTlPan,
            setTlZoom,
            syncBackendManagerFlowGraph,
            timeAxisY,
            timeTicks,
            timelineViewportRef,
            tlDragging,
            tlPan,
            tlZoom,
            visibleEdges,
            visibleNodes,
            visibleNodesByPosition,
            visibleTimelineProofCount,
            xOffset,
            zoomDetail,
            zoomScale,
          }}
        />
    );
}

