import {
  Activity,
  BadgeCheck,
  BellDot,
  CheckCircle2,
  CircleDot,
  Database,
  FileCheck2,
  FileText,
  Landmark,
  Lightbulb,
  MessageSquare,
  Network,
  NotebookText,
  Radar,
  RotateCcw,
  ScanEye,
  ScrollText,
  Shield,
  Sparkles,
  Users,
  X,
} from 'lucide-react';
import AdvancedProjectTimeline from './AdvancedProjectTimeline.jsx';
import {
  WORKFLOW_NODE_FAMILIES,
  WORKFLOW_NODE_FAMILY_ORDER,
  WORKFLOW_NODE_SCALES,
  decorateWorkflowNode,
  workflowNodeVisibleAtScale,
} from '../workflow/workflowNodeProtocol.js';
import {
  buildWorkflowTimelineDisplayNodes,
  centerTimelineNodePan,
  clampTimelinePan,
  fitTimelineCanvasZoom,
  planWorkflowTimelineLayout,
  preserveTimelineViewportAnchor,
} from '../workflow/workflowTimelineLayout.js';

export default function ProjectTimelineRouteView({ view }) {
  const {
    DEFAULT_CHAT_PROJECT_ID,
    activeProject,
    allowLocalRuntimeFallbackForActiveProject,
    backendStation,
    chatChannels,
    chatMessages,
    chatProofIdsFromAttachment,
    chatProofIdsFromNode,
    confirmManagerFlowNode,
    exitProjectScene,
    focusedTimelineProofIds,
    isManagerDemoProject,
    openProjectChatProof,
    openProjectTimelineProof,
    projectText,
    renderAutonomousActionDecision,
    sceneTransition,
    selectedTimelineEventId,
    setFocusedTimelineProofIds,
    setSelectedTimelineEventId,
    setTimelineScale,
    setTlDragging,
    setTlPan,
    setTlZoom,
    shouldAttemptBackendProjectWrite,
    syncBackendManagerFlowGraph,
    timelineScale,
    timelineViewportRef,
    tlDragStartRef,
    tlDragging,
    tlPan,
    tlZoom,
  } = view;

    const iconByKey = {
      activity: Activity,
      'badge-check': BadgeCheck,
      database: Database,
      'file-check': FileCheck2,
      landmark: Landmark,
      lightbulb: Lightbulb,
      'message-square': MessageSquare,
      'notebook-text': NotebookText,
      radar: Radar,
      'rotate-ccw': RotateCcw,
      'scan-check': ScanEye,
      shield: Shield,
      sparkles: Sparkles,
      users: Users,
    };
    const categoryMeta = Object.fromEntries(WORKFLOW_NODE_FAMILY_ORDER.map((id) => [id, {
      ...WORKFLOW_NODE_FAMILIES[id],
      Icon: iconByKey[WORKFLOW_NODE_FAMILIES[id].iconKey] || CircleDot,
    }]));
    const channelNameById = Object.fromEntries(chatChannels.map(channel => [channel.id, channel.name]));
    const categoryOrder = WORKFLOW_NODE_FAMILY_ORDER;
    const edgeMeta = {
      leader_assignment: { label: 'Leader assignment', color: '#8f1e18' },
      agent_collaboration: { label: 'Agent collaboration', color: '#59684b' },
      task_dependency: { label: 'Task dependency', color: '#bcae86' },
      change_impact: { label: 'Change impact', color: '#b9782b' },
      reporting: { label: 'Report line', color: '#d8c99f' },
      evidence: { label: 'Evidence line', color: '#7b6542' },
    };
    const localAttachmentTypeFor = (node) => {
      const text = `${node.category || ''} ${node.subtype || ''} ${node.source || ''}`.toLowerCase();
      if (/meeting/.test(text)) return 'meeting-minutes';
      if (/report|summary|submission/.test(text)) return 'report';
      if (/test/.test(text)) return 'test-result';
      if (/heartbeat|monitor|loop/.test(text)) return 'runtime-check';
      if (/message|chat|communication/.test(text)) return 'chat-record';
      if (/evidence|proof/.test(text)) return 'evidence-packet';
      return 'workflow-attachment';
    };
    const localSubmissionIntentFor = (node) => {
      const text = `${node.category || ''} ${node.subtype || ''}`.toLowerCase();
      if (/meeting/.test(text)) return 'Submit meeting minutes and attendance evidence.';
      if (/report|summary|submission/.test(text)) return 'Submit a deliverable report for manager/user review.';
      if (/heartbeat|monitor|loop/.test(text)) return 'Submit an Agent runtime check-in.';
      if (/message|chat|communication/.test(text)) return 'Submit a communication record with receipt context.';
      return 'Submit an Agent-authored workflow commit for manager review.';
    };
    const withLocalSubmissionArtifacts = (node) => {
      const attachment = {
        id: `${node.id}_attachment_main`,
        type: localAttachmentTypeFor(node),
        title: `${node.title} attachment`,
        summary: node.summary,
        source: node.source,
        autoGenerated: true,
        proofIds: node.proofIds || [],
        timelineLogIds: node.timelineLogIds || [],
        eventIds: node.eventIds || [],
        taskId: node.taskId || null,
        route: node.route || null,
      };
      const field = (id, label, source, value, required = true) => ({
        id,
        label,
        source,
        required,
        status: required && (value === null || value === undefined || value === '' || (Array.isArray(value) && !value.length)) ? 'missing' : 'filled',
      });
      return {
        ...node,
        commitMessage: node.commitMessage || node.summary || node.title,
        committerIds: node.committerIds || [node.agentId].filter(Boolean),
        attachments: node.attachments?.length ? node.attachments : [attachment],
        submission: node.submission || {
          id: `submission_${node.id}`,
          generatedBy: 'manager-flow-fallback-protocol',
          intent: localSubmissionIntentFor(node),
          commitMessage: node.commitMessage || node.summary || node.title,
          submittedByAgentId: node.agentId || null,
          submittedByAgentName: node.agentName || 'Project',
          committerIds: node.committerIds || [node.agentId].filter(Boolean),
          coAuthorIds: node.coAuthorIds || [],
          participantIds: node.participantIds || node.affectedAgentIds || [],
          attachmentIds: [attachment.id],
          requiredFields: [
            field('category', 'Category', 'agent', node.category),
            field('subtype', 'Subtype', 'agent', node.subtype),
            field('commitMessage', 'Commit message', 'agent', node.commitMessage || node.summary || node.title),
            field('submitter', 'Submitting Agent', 'agent', node.agentId || node.agentName),
            field('attachments', 'Submitted artifact attachment', 'agent', [attachment]),
          ],
          autoFields: [
            field('id', 'Node ID', 'system', node.id, false),
            field('time', 'Commit time', 'system', node.time, false),
            field('status', 'Workflow status', 'system', node.status, false),
            field('source', 'Source ledger', 'system', node.source, false),
          ],
        },
      };
    };
    const activeFlowGraphProjectId = String(activeProject.id || '').toLowerCase();
    const backendFlowGraphFromStation = String(backendStation.managerFlowGraph?.projectId || '').toLowerCase() === activeFlowGraphProjectId
      ? backendStation.managerFlowGraph
      : null;
    const backendReadyPackageForFlowGraph = String(backendStation.managerReadyPackage?.projectId || '').toLowerCase() === activeFlowGraphProjectId
      ? backendStation.managerReadyPackage
      : null;
    const backendFlowGraph = backendFlowGraphFromStation || backendReadyPackageForFlowGraph?.managerFlowGraph || null;
    const backendDashboardForFlowGraph = String(backendStation.managerDashboard?.projectId || '').toLowerCase() === activeFlowGraphProjectId
      ? backendStation.managerDashboard
      : null;
    const backendProofMapFromStationForFlowGraph = String(backendStation.readinessProofMap?.projectId || '').toLowerCase() === activeFlowGraphProjectId
      ? backendStation.readinessProofMap
      : null;
    const backendReadinessProofMapForFlowGraph = backendProofMapFromStationForFlowGraph
      || backendDashboardForFlowGraph?.readinessProofMap
      || backendReadyPackageForFlowGraph?.managerDashboard?.readinessProofMap
      || backendReadyPackageForFlowGraph?.readinessProofMap
      || null;
    const backendTimelineProofMap = backendReadinessProofMapForFlowGraph || null;
    const buildFallbackFlowGraph = () => {
      const agentStatusNodes = activeProject.team.map((agent, index) => {
        const state = activeProject.agentStates?.[agent.id] || {};
        return {
          id: `agent-status-${agent.id}`,
          category: 'monitoring',
          subtype: 'agent-heartbeat',
          title: `${agent.name} current state`,
          agentId: agent.id,
          agentName: agent.name,
          taskId: null,
          time: state.lastActiveAt || activeProject.updatedAt || activeProject.createdAt || new Date().toISOString(),
          summary: state.currentPlan?.focus || state.status || 'Waiting for backend graph sync.',
          status: state.status === 'blocked' ? 'blocked' : 'published',
          importance: index === 0 ? 'major' : 'normal',
          source: 'agentStates',
          proofIds: [],
          relatedNodeIds: [],
          timelineLogIds: [],
          eventIds: [],
        };
      });
      const logNodes = (activeProject.logs || []).slice(0, 24).map((log, index) => {
        const agent = activeProject.team.find(member => member.id === log.agentId || member.name === log.agent);
        const category = /confirmed|approved|decision/i.test(log.eventType || '')
          ? 'decision'
          : /report|completed|test/i.test(log.eventType || '')
            ? 'submission'
            : /management|worker|scheduler/i.test(log.eventType || '')
              ? 'monitoring'
              : 'execution';
        return {
          id: `timeline-log-${log.id || index}`,
          category,
          subtype: log.eventType || 'timeline-log',
          title: log.agent || log.actor || log.eventType || 'Timeline log',
          agentId: log.agentId || agent?.id || null,
          agentName: agent?.name || log.agent || 'Runtime',
          taskId: log.taskId || null,
          time: log.time || activeProject.updatedAt || activeProject.createdAt || new Date().toISOString(),
          summary: log.log || log.text || 'Timeline log',
          status: /blocked/i.test(log.eventType || '') ? 'blocked' : 'published',
          importance: index < 6 ? 'major' : 'normal',
          source: 'timeline logs',
          sourceChannelId: log.sourceChannelId || null,
          receiptCount: log.receiptCount || 0,
          directTargetIds: log.directTargetIds || [],
          proofIds: [String(log.id || '').startsWith('log_') ? String(log.id).slice(4) : null].filter(Boolean),
          timelineLogIds: [log.id].filter(Boolean),
          eventIds: [],
          relatedNodeIds: log.agentId ? [`agent-status-${log.agentId}`] : [],
          attachments: log.attachments || [],
        };
      });
      const nodes = [...agentStatusNodes, ...logNodes].map((node, index) => ({
        ...node,
        sequence: index + 1,
        categoryLabel: categoryMeta[node.category]?.label || node.category,
        hasProof: Boolean(node.proofIds?.length || node.timelineLogIds?.length || node.eventIds?.length),
      })).map(withLocalSubmissionArtifacts);
      const edges = logNodes
        .filter(node => node.agentId)
        .map(node => ({
          id: `fallback-edge-${node.id}`,
          type: node.category === 'submission' ? 'reporting' : 'task_dependency',
          typeLabel: node.category === 'submission' ? 'Report line' : 'Task dependency line',
          fromNodeId: `agent-status-${node.agentId}`,
          toNodeId: node.id,
          label: node.category === 'submission' ? 'Agent report' : 'Agent progress',
          status: 'published',
          importance: node.importance,
          source: node.source,
          proofIds: node.proofIds || [],
          timelineLogIds: node.timelineLogIds || [],
          eventIds: [],
        }));
      const byCategory = nodes.reduce((acc, node) => ({ ...acc, [node.category]: (acc[node.category] || 0) + 1 }), {});
      return {
        projectId: activeProject.id,
        schemaVersion: 'manager-flow-graph/fallback',
        generatedAt: new Date().toISOString(),
        categories: categoryOrder.map(id => ({ id, ...categoryMeta[id], count: byCategory[id] || 0 })),
        summary: {
          nodeCount: nodes.length,
          edgeCount: edges.length,
          proofedNodeCount: nodes.filter(node => node.hasProof).length,
          confirmedNodeCount: nodes.filter(node => node.status === 'confirmed').length,
          blockedNodeCount: nodes.filter(node => node.status === 'blocked').length,
          majorVisibleCount: nodes.filter(node => ['major', 'critical'].includes(node.importance)).length,
          byCategory,
        },
        zoomRules: {
          compact: { label: 'Major and critical only', importances: ['major', 'critical'] },
          medium: { label: 'Agent working path' },
          expanded: { label: 'Chat, report, evidence, and detail' },
        },
        dataSources: {
          eventLedger: activeProject.eventLedger?.length || 0,
          timelineLogs: activeProject.logs?.length || 0,
          messages: chatMessages.filter(message => (message.projectId || DEFAULT_CHAT_PROJECT_ID) === activeProject.id).length,
          tasks: activeProject.tasks?.length || 0,
          agentStates: Object.keys(activeProject.agentStates || {}).length,
          kickoffCharter: Boolean(activeProject.kickoffCharter),
          changeLedger: activeProject.changeLedger?.length || 0,
          managerDashboard: Boolean(backendDashboardForFlowGraph),
        },
        nodes,
        edges,
      };
    };
    const backendOnline = backendStation.connectionStatus === 'online';
    const backendCommandAvailable = shouldAttemptBackendProjectWrite(activeProject);
    const allowFlowFrontendFallbacks = allowLocalRuntimeFallbackForActiveProject(activeProject);
    const backendFlowGraphReady = Boolean(backendFlowGraph?.nodes?.length);
    const missingBackendFlowGraph = {
      projectId: activeProject.id,
      schemaVersion: 'manager-flow-graph/missing-backend',
      generatedAt: new Date().toISOString(),
      dataSource: 'backend-required',
      status: 'backend-model-missing',
      frontendMockSuppressed: true,
      frontendFallbackMode: 'backend-required',
      categories: categoryOrder.map(id => ({ id, ...categoryMeta[id], count: 0 })),
      summary: {
        nodeCount: 0,
        edgeCount: 0,
        proofedNodeCount: 0,
        confirmedNodeCount: 0,
        blockedNodeCount: 0,
        majorVisibleCount: 0,
        byCategory: {},
      },
      zoomRules: {
        compact: { label: 'Major and critical only', importances: ['major', 'critical'] },
        medium: { label: 'Agent working path' },
        expanded: { label: 'Chat, report, evidence, and detail' },
      },
      dataSources: {
        managerFlowGraphRoute: `/projects/${activeProject.id}/manager-flow-graph`,
        managerReadyPackage: Boolean(backendReadyPackageForFlowGraph),
        managerDashboard: Boolean(backendDashboardForFlowGraph),
      },
      nodes: [],
      edges: [],
    };
    const managerFlowGraph = backendFlowGraphReady
      ? { ...backendFlowGraph, dataSource: backendFlowGraph.dataSource || 'backend-backed' }
      : allowFlowFrontendFallbacks
        ? {
            ...buildFallbackFlowGraph(),
            dataSource: 'frontend-fallback',
            frontendFallbackMode: 'demo-or-offline',
            demoOnly: isManagerDemoProject(activeProject),
          }
        : missingBackendFlowGraph;
    const managerFlowGraphSourceLabel = managerFlowGraph.frontendMockSuppressed
      ? 'backend model missing'
      : managerFlowGraph.dataSource === 'frontend-fallback'
        ? 'demo data'
        : 'backend-backed';
    const scaleProfiles = Object.fromEntries(Object.entries(WORKFLOW_NODE_SCALES).map(([id, profile]) => [id, {
      ...profile,
      test: node => workflowNodeVisibleAtScale(node, id),
    }]));
    const scaleOrder = Object.keys(WORKFLOW_NODE_SCALES);
    const zoomDetail = tlZoom < 0.72 ? 'compact' : tlZoom < 1.12 ? 'medium' : 'expanded';
    const zoomScale = tlZoom < 0.72 ? 'month' : tlZoom < 1.04 ? 'week' : tlZoom < 1.42 ? 'day' : 'hour';
    const activeScaleProfile = scaleProfiles[zoomScale] || scaleProfiles.day;
    const decoratedGraphNodes = (managerFlowGraph.nodes || []).map(decorateWorkflowNode);
    const semanticNodes = Array.from(new Map(decoratedGraphNodes
      .filter(activeScaleProfile.test)
      .map(node => [node.id, node])).values())
      .sort((a, b) => {
        const areaA = a.commitArea?.index ?? managerFlowGraph.layout?.nodeLayoutHints?.[a.id]?.index;
        const areaB = b.commitArea?.index ?? managerFlowGraph.layout?.nodeLayoutHints?.[b.id]?.index;
        if (Number.isFinite(areaA) && Number.isFinite(areaB) && areaA !== areaB) return areaA - areaB;
        const timeA = Date.parse(a.time) || 0;
        const timeB = Date.parse(b.time) || 0;
        if (timeA !== timeB) return timeA - timeB;
        const branchA = a.commitArea?.branchIndex ?? managerFlowGraph.layout?.nodeLayoutHints?.[a.id]?.branchIndex;
        const branchB = b.commitArea?.branchIndex ?? managerFlowGraph.layout?.nodeLayoutHints?.[b.id]?.branchIndex;
        if (Number.isFinite(branchA) && Number.isFinite(branchB) && branchA !== branchB) return branchA - branchB;
        return (a.sequence || 0) - (b.sequence || 0);
      });
    const timelineDisplay = buildWorkflowTimelineDisplayNodes({ nodes: semanticNodes, scale: zoomScale });
    const visibleNodes = timelineDisplay.nodes;
    const visibleNodeIds = new Set(visibleNodes.map(node => node.id));
    const visibleEdges = Array.from(new Map((managerFlowGraph.edges || [])
      .map((edge) => {
        const fromNodeId = timelineDisplay.memberToDisplayId.get(edge.fromNodeId) || edge.fromNodeId;
        const toNodeId = timelineDisplay.memberToDisplayId.get(edge.toNodeId) || edge.toNodeId;
        if (fromNodeId === toNodeId || !visibleNodeIds.has(fromNodeId) || !visibleNodeIds.has(toNodeId)) return null;
        return [`${fromNodeId}|${toNodeId}|${edge.type || 'task_dependency'}`, {
          ...edge,
          id: `${edge.id || 'flow-edge'}-${fromNodeId}-${toNodeId}`,
          fromNodeId,
          toNodeId,
        }];
      })
      .filter(Boolean)).values());
    const nodeMap = Object.fromEntries([...decoratedGraphNodes, ...visibleNodes].map(node => [node.id, node]));
    const selectedDisplayId = timelineDisplay.memberToDisplayId.get(selectedTimelineEventId) || selectedTimelineEventId;
    const selectedNode = visibleNodes.find(node => node.id === selectedDisplayId)
      || visibleNodes.find(node => [node.id, ...(node.clusterMemberIds || []), ...(node.proofIds || []), ...(node.timelineLogIds || []), ...(node.eventIds || [])].includes(selectedTimelineEventId))
      || decoratedGraphNodes.find(node => node.id === selectedTimelineEventId)
      || null;
    const selectedThinkingFrame = selectedNode?.thinkingFrame || selectedNode?.submission?.thinkingFrame || null;
    const relatedEdges = selectedNode
      ? visibleEdges.filter(edge => edge.fromNodeId === selectedNode.id || edge.toNodeId === selectedNode.id)
      : [];
    const relatedNodeIds = selectedNode
      ? Array.from(new Set(relatedEdges.flatMap(edge => [edge.fromNodeId, edge.toNodeId]).filter(id => id !== selectedNode.id)))
      : [];
    const isProofFocused = (node) => focusedTimelineProofIds.some(id => (
      node.id === id
      || (node.proofIds || []).includes(id)
      || (node.timelineLogIds || []).includes(id)
      || (node.eventIds || []).includes(id)
    ));
    const visibleTimelineProofCount = visibleNodes.filter(isProofFocused).length;
    const uniqueIds = (values) => Array.from(new Set((values || []).filter(Boolean).map(value => String(value))));
    const agentById = new Map((activeProject.team || []).map(agent => [agent.id, agent]));
    const agentDisplay = (agentId) => {
      const agent = agentById.get(agentId);
      return {
        id: agentId || 'project',
        name: agent?.name || agentId || 'Project',
        role: agent?.title || agent?.role || agent?.duty || (agentId ? 'Agent' : 'Project'),
        accent: agent?.color || '#bcae86',
      };
    };
    const nodeCommitters = (node) => uniqueIds([
      ...(node.committerIds || []),
      node.agentId,
      ...(node.coAuthorIds || []),
    ]).map(agentDisplay);
    const committersLabel = (node) => {
      const committers = nodeCommitters(node);
      if (!committers.length) return node.agentName || 'Project';
      if (committers.length === 1) return committers[0].name;
      return `${committers.slice(0, 2).map(person => person.name).join(' + ')}${committers.length > 2 ? ` +${committers.length - 2}` : ''}`;
    };
    const compactText = (value, max = 96) => {
      const text = String(value || '').replace(/\s+/g, ' ').trim();
      if (text.length <= max) return text;
      return `${text.slice(0, Math.max(0, max - 3)).trim()}...`;
    };
    const timelineLayout = planWorkflowTimelineLayout({ nodes: visibleNodes, scale: zoomScale, detail: zoomDetail });
    const {
      canvasH,
      canvasW,
      laneGuides,
      nodeLayout,
      rulerHeight,
      timeTicks,
      xOffset,
    } = timelineLayout;
    const visibleNodesByPosition = visibleNodes
      .map(node => ({ node, box: nodeLayout[node.id] }))
      .filter(item => item.box)
      .sort((a, b) => a.box.x - b.box.x || a.box.y - b.box.y)
      .map(item => item.node);
    const initialGraphNode = selectedNode || visibleNodesByPosition[0] || null;
    const initialGraphNodeBox = initialGraphNode ? nodeLayout[initialGraphNode.id] : null;
    const defaultGraphPan = initialGraphNodeBox
      ? { x: 300 - initialGraphNodeBox.x, y: 180 - initialGraphNodeBox.y }
      : { x: 0, y: 0 };
    const getAnchor = (edge) => {
      const from = nodeLayout[edge.fromNodeId];
      const to = nodeLayout[edge.toNodeId];
      if (!from || !to) return null;
      const forward = to.x >= from.x;
      const sx = forward ? from.x + from.w : from.x;
      const sy = from.y + from.h / 2;
      const ex = forward ? to.x : to.x + to.w;
      const ey = to.y + to.h / 2;
      const bendX = forward && ex - sx > 80 ? (sx + ex) / 2 : Math.max(sx, ex) + 64;
      return { sx, sy, ex, ey, path: `M ${sx} ${sy} H ${bendX} V ${ey} H ${ex}` };
    };
    const graphViewport = () => {
      const viewport = timelineViewportRef.current;
      return viewport ? { width: viewport.clientWidth, height: viewport.clientHeight } : null;
    };
    const clampGraphPan = (pan, zoom = tlZoom) => clampTimelinePan({
      pan,
      zoom,
      canvas: { width: canvasW, height: canvasH },
      viewport: graphViewport(),
    });
    const focusGraphNode = (nodeId, zoom = tlZoom) => {
      const viewport = graphViewport();
      const box = nodeLayout[nodeId];
      if (!viewport || !box) return false;
      setTlPan(clampGraphPan(centerTimelineNodePan({ box, viewport, zoom }), zoom));
      return true;
    };
    const handleGraphZoomChange = (nextZoomValue) => {
      const nextZoom = Math.min(2.2, Math.max(0.36, Number(nextZoomValue) || 1));
      const viewport = graphViewport();
      if (!viewport) {
        setTlZoom(nextZoom);
        return;
      }
      const selectedBox = selectedNode ? nodeLayout[selectedNode.id] : null;
      const worldPoint = selectedBox
        ? { x: selectedBox.x + selectedBox.w / 2, y: selectedBox.y + selectedBox.h / 2 }
        : { x: (viewport.width / 2 - tlPan.x) / tlZoom, y: (viewport.height / 2 - tlPan.y) / tlZoom };
      const viewportPoint = selectedBox
        ? { x: tlPan.x + worldPoint.x * tlZoom, y: tlPan.y + worldPoint.y * tlZoom }
        : { x: viewport.width / 2, y: viewport.height / 2 };
      const nextPan = preserveTimelineViewportAnchor({ worldPoint, viewportPoint, zoom: nextZoom });
      setTlZoom(nextZoom);
      setTlPan(clampGraphPan(nextPan, nextZoom));
    };
    const fitGraphView = () => {
      const viewport = graphViewport();
      if (!viewport) return;
      const nextZoom = fitTimelineCanvasZoom({
        canvas: { width: canvasW, height: canvasH },
        viewport,
        minZoom: 0.36,
        maxZoom: 1,
      });
      const nextPan = preserveTimelineViewportAnchor({
        worldPoint: { x: canvasW / 2, y: canvasH / 2 },
        viewportPoint: { x: viewport.width / 2, y: viewport.height / 2 },
        zoom: nextZoom,
      });
      setTlZoom(nextZoom);
      setTlPan(clampGraphPan(nextPan, nextZoom));
    };
    const focusSelectedNode = () => selectedNode && focusGraphNode(selectedNode.id);
    const focusLatestNode = () => {
      const latest = [...visibleNodes].sort((a, b) => (
        (Date.parse(b.time) || 0) - (Date.parse(a.time) || 0) || (b.sequence || 0) - (a.sequence || 0)
      ))[0];
      if (!latest) return;
      setSelectedTimelineEventId(latest.id);
      focusGraphNode(latest.id);
    };
    const handleGraphWheel = (event) => {
      event.preventDefault();
      if (event.altKey) {
        const current = scaleOrder.indexOf(timelineScale);
        const next = event.deltaY > 0 ? Math.max(0, current - 1) : Math.min(scaleOrder.length - 1, current + 1);
        setTimelineScale(scaleOrder[next]);
        return;
      }
      if (event.shiftKey) {
        setTlPan(prev => ({ ...prev, x: prev.x - event.deltaY }));
        return;
      }
      const rect = event.currentTarget.getBoundingClientRect();
      const pointerX = event.clientX - rect.left;
      const pointerY = event.clientY - rect.top;
      const nextZoom = Math.min(2.2, Math.max(0.36, tlZoom * Math.exp(-event.deltaY * 0.0012)));
      const worldX = (pointerX - tlPan.x) / tlZoom;
      const worldY = (pointerY - tlPan.y) / tlZoom;
      setTlZoom(nextZoom);
      setTlPan(clampGraphPan({
        x: pointerX - worldX * nextZoom,
        y: pointerY - worldY * nextZoom,
      }, nextZoom));
    };
    const handleGraphMouseDown = (event) => {
      if (event.target.closest('button')) return;
      setTlDragging(true);
      tlDragStartRef.current = { x: event.clientX, y: event.clientY, panX: tlPan.x, panY: tlPan.y };
    };
    const handleGraphMouseMove = (event) => {
      if (!tlDragging) return;
      setTlPan(clampGraphPan({
        x: tlDragStartRef.current.panX + event.clientX - tlDragStartRef.current.x,
        y: tlDragStartRef.current.panY + event.clientY - tlDragStartRef.current.y,
      }));
    };
    const resetGraphView = () => {
      setTlZoom(1);
      setTimelineScale('day');
      const latest = [...visibleNodes].sort((a, b) => (Date.parse(b.time) || 0) - (Date.parse(a.time) || 0))[0];
      if (latest) {
        setSelectedTimelineEventId(latest.id);
        focusGraphNode(latest.id, 1);
      } else {
        setTlPan({ x: 0, y: 0 });
      }
    };
    const graphTime = (value) => {
      if (!value) return 'No time';
      const clockOnly = String(value).trim().match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);
      if (clockOnly) {
        const hour = String(Math.min(23, Number(clockOnly[1]))).padStart(2, '0');
        return `${hour}:${clockOnly[2]}`;
      }
      const parsed = new Date(value);
      if (Number.isNaN(parsed.getTime())) return String(value);
      const date = parsed.toLocaleDateString(undefined, { year: 'numeric', month: '2-digit', day: '2-digit' });
      const time = parsed.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', hour12: false });
      return `${date} ${time}`;
    };
    const selectedChatProofIds = selectedNode ? chatProofIdsFromNode(selectedNode) : [];
    const selectedProofRouteCandidates = selectedNode ? [
      selectedNode.route,
      selectedNode.proofRoute,
      selectedNode.apiPath,
      selectedNode.backendRoutes?.runtimeAutonomyStatus,
      selectedNode.id === 'runtime-autonomy-status' || selectedNode.source === 'runtimeAutonomyStatus'
        ? `/projects/${activeProject.id}/runtime-autonomy-status`
        : null,
      selectedNode.submission?.route,
      selectedNode.submission?.proofRoute,
      selectedNode.submission?.apiPath,
      ...(selectedNode.attachments || []).map(attachment => attachment.route),
    ].filter(Boolean).map(value => String(value)) : [];
    const selectedNodeRawProofRoute = selectedProofRouteCandidates.find(route => route.startsWith('/projects/'))
      || selectedProofRouteCandidates[0]
      || null;
    const routeCollection = (key) => (backendTimelineProofMap?.[key] || []).map(route => ({ ...route, proofMapKey: key }));
    const selectedNodeProofMapRoutes = (selectedNode ? [
      ...routeCollection('submissionRoutes'),
      ...routeCollection('revisionRoutes'),
      ...routeCollection('evidenceSearchRoutes'),
      ...routeCollection('submissionReviewRoutes'),
      ...routeCollection('sourceReviewRoutes'),
      ...routeCollection('evidenceSourceReviewRoutes'),
      ...routeCollection('brainstormLayerRoutes'),
      ...routeCollection('artifactQualityRoutes'),
      ...routeCollection('evidenceQualityRoutes'),
      ...routeCollection('submissionReviewWorkflowRoutes'),
      ...routeCollection('productTeamDeliveryTraceRoutes'),
      ...routeCollection('productTeamAcceptanceChainRoutes'),
      ...routeCollection('productTeamMissionRunRoutes'),
      ...routeCollection('runtimeAutonomyStatusRoutes'),
      ...(backendTimelineProofMap?.routes || []).map(route => ({ ...route, proofMapKey: 'routes' })),
    ] : []).filter(route => {
      const apiPath = route.apiPath || route.route || route.proofRoute;
      if (selectedNodeRawProofRoute && apiPath === selectedNodeRawProofRoute) return true;
      const proofOverlap = (route.proofIds || []).some(id => selectedChatProofIds.includes(id) || (selectedNode.proofIds || []).includes(id));
      const timelineOverlap = (route.timelineLogIds || []).some(id => (selectedNode.timelineLogIds || []).includes(id));
      const eventOverlap = (route.eventIds || []).some(id => (selectedNode.eventIds || []).includes(id));
      return proofOverlap || timelineOverlap || eventOverlap;
    });
    const selectedNodeExactProofMapRoute = selectedNodeRawProofRoute
      ? selectedNodeProofMapRoutes.find(route => (route.apiPath || route.route || route.proofRoute) === selectedNodeRawProofRoute)
      : null;
    const selectedNodeProofMapRoute = selectedNodeExactProofMapRoute || selectedNodeProofMapRoutes[0] || null;
    const selectedNodeProofRoute = selectedNodeRawProofRoute
      || selectedNodeProofMapRoute?.apiPath
      || selectedNodeProofMapRoute?.route
      || selectedNodeProofMapRoute?.proofRoute
      || null;
    const selectedNodeProofMapKey = selectedNodeProofMapRoute?.proofMapKey || (selectedNodeProofRoute ? 'flow-node-route' : 'not-linked');
    const selectedNodeSubmissionRouteCandidates = selectedNode ? [
      selectedNode.submission?.route,
      selectedNode.submission?.proofRoute,
      selectedNode.submission?.apiPath,
      selectedNode.submissionRoute,
      selectedNode.route,
      selectedNode.proofRoute,
      selectedNode.apiPath,
      ...(selectedNode.attachments || []).map(attachment => attachment.submissionRoute || attachment.route),
    ].filter(Boolean).map(value => String(value)).filter(route => route.includes('/submissions/')) : [];
    const selectedNodeSubmissionRoute = selectedNodeSubmissionRouteCandidates[0] || null;
    const selectedNodeSubmissionId = selectedNode
      ? (
          selectedNode.submission?.id
          || selectedNode.submissionId
          || selectedNode.resourceId
          || selectedNodeSubmissionRoute?.split('/submissions/')[1]?.split(/[?#/]/)[0]
          || (String(selectedNode.id || '').startsWith('agent-submission-') ? String(selectedNode.id).replace(/^agent-submission-/, '') : null)
        )
      : null;
    const selectedNodeHasSubmissionRecord = Boolean(selectedNodeSubmissionRoute || selectedNodeSubmissionId);
    const openSelectedNodeProofMapRoute = () => {
      exitProjectScene();
      window.setTimeout(() => {
        document.querySelector('[data-testid="manager-proof-map"]')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 540);
    };
    const openSelectedNodeSubmissionRecord = () => {
      if (!selectedNodeHasSubmissionRecord) return;
      exitProjectScene();
      const targetTestId = selectedNodeSubmissionId ? `backend-manager-submission-row-${selectedNodeSubmissionId}` : null;
      window.setTimeout(() => {
        const exactTarget = targetTestId
          ? Array.from(document.querySelectorAll('[data-testid]')).find(element => element.getAttribute('data-testid') === targetTestId)
          : null;
        const fallbackTarget = document.querySelector('[data-testid="backend-manager-submissions-snapshot"]');
        (exactTarget || fallbackTarget)?.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }, 540);
    };
    const connectedPeople = selectedNode
      ? uniqueIds([
        ...(selectedNode.committerIds || []),
        selectedNode.agentId,
        ...(selectedNode.coAuthorIds || []),
        ...(selectedNode.participantIds || []),
        ...(selectedNode.affectedAgentIds || []),
        ...relatedNodeIds.map(id => nodeMap[id]?.agentId),
      ]).map(agentId => {
        const person = agentDisplay(agentId);
        const relationshipRoles = selectedNode.relationshipRoles || {};
        const role = relationshipRoles[agentId]
          || ((selectedNode.committerIds || []).includes(agentId) || selectedNode.agentId === agentId ? 'primary-committer' : null)
          || ((selectedNode.coAuthorIds || []).includes(agentId) ? 'co-committer' : null)
          || ((selectedNode.participantIds || []).includes(agentId) ? 'participant' : null)
          || ((selectedNode.affectedAgentIds || []).includes(agentId) ? 'impacted' : 'related');
        return { ...person, relation: role };
      })
      : [];
    const relationshipGraph = (() => {
      const width = 370;
      const height = 250;
      const center = { x: width / 2, y: height / 2 };
      const radiusX = 138;
      const radiusY = 84;
      const people = connectedPeople.map((person, index) => {
        const angle = connectedPeople.length === 1 ? -Math.PI / 2 : (-Math.PI / 2) + (index * Math.PI * 2) / connectedPeople.length;
        return {
          ...person,
          x: center.x + Math.cos(angle) * radiusX,
          y: center.y + Math.sin(angle) * radiusY,
        };
      });
      return { width, height, center, people };
    })();

    return (
      <AdvancedProjectTimeline
          view={{
            CheckCircle2,
            CircleDot,
            Database,
            FileText,
            MessageSquare,
            Network,
            ScrollText,
            X,
            activeProject,
            agentDisplay,
            backendCommandAvailable,
            backendStation,
            canvasH,
            canvasW,
            categoryMeta,
            categoryOrder,
            channelNameById,
            chatProofIdsFromAttachment,
            committersLabel,
            compactText,
            confirmManagerFlowNode,
            connectedPeople,
            defaultGraphPan,
            edgeMeta,
            exitProjectScene,
            focusedTimelineProofIds,
            fitGraphView,
            focusGraphNode,
            focusLatestNode,
            focusSelectedNode,
            getAnchor,
            graphTime,
            handleGraphMouseDown,
            handleGraphMouseMove,
            handleGraphWheel,
            handleGraphZoomChange,
            isProofFocused,
            managerFlowGraph,
            managerFlowGraphSourceLabel,
            laneGuides,
            nodeCommitters,
            nodeLayout,
            nodeMap,
            openProjectChatProof,
            openProjectTimelineProof,
            projectText,
            openSelectedNodeProofMapRoute,
            openSelectedNodeSubmissionRecord,
            relatedEdges,
            relatedNodeIds,
            relationshipGraph,
            renderAutonomousActionDecision,
            resetGraphView,
            rulerHeight,
            scaleProfiles,
            sceneTransition,
            selectedChatProofIds,
            selectedNode,
            selectedNodeHasSubmissionRecord,
            selectedNodeProofMapKey,
            selectedNodeProofMapRoutes,
            selectedNodeProofRoute,
            selectedNodeSubmissionId,
            selectedNodeSubmissionRoute,
            selectedThinkingFrame,
            setFocusedTimelineProofIds,
            setSelectedTimelineEventId,
            setTlDragging,
            setTlPan,
            syncBackendManagerFlowGraph,
            timeTicks,
            timelineViewportRef,
            tlDragging,
            tlPan,
            tlZoom,
            visibleEdges,
            visibleNodes,
            visibleNodesByPosition,
            visibleTimelineProofCount,
            xOffset,
            zoomDetail,
            zoomScale,
          }}
        />
    );
}
