import React from 'react';

export default function ProjectDashboardManagerReadyPackageSummary({
  formatters,
  models,
  projectText,
  readyPackage,
}) {
  const {
    modelBoolean,
    modelCents,
    modelRatio,
    modelStatus,
    modelValue,
    summaryBoolean,
    summaryRatio,
    summaryStatus,
    summaryValue,
  } = formatters;
  const {
    adapterGatewayPreflight,
    artifactQualityAudit,
    autonomousCycleConsistency,
    collaborationIntentQueue,
    deploymentPreflight,
    evidenceCustodyReadiness,
    evidenceIndexReadiness,
    evidenceQualityAudit,
    evidenceSourceReviewWorkflow,
    launchApprovalWorkflow,
    mvpReadiness,
    operationsReadiness,
    pilotLaunchReadiness,
    privatePilotAcceptanceReportWorkflow,
    privatePilotGoLiveReadiness,
    privatePilotLaunchHealthCheckWorkflow,
    privatePilotLaunchRunWorkflow,
    privatePilotReleaseCandidateWorkflow,
    productionInfrastructureRehearsal,
    productionLaunchAudit,
    productionOperationsControlReceiptWorkflow,
    productionOperationsReadiness,
    productTeamDeliveryTrace,
    productTeamOperatingLoop,
    projectEvidenceArchive,
    projectEvidenceExportWorkflow,
    providerControlledRun,
    providerEvalRunWorkflow,
    providerReadiness,
    runtimeAutonomyStatus,
    runtimeContracts,
    securityBoundary,
    submissionReviewWorkflow,
    teamCollaborationDiagnostics,
  } = models;

  const rows = [
    ['Status', readyPackage.status || 'unknown'],
    ['Score', readyPackage.score ?? 0],
    ['MVP Status', readyPackage.mvpStatus || mvpReadiness?.status || 'unknown'],
    ['Local Pilot', readyPackage.readyForLocalPilot ? 'ready' : 'blocked'],
    ['Production', readyPackage.readyForProduction ? 'ready' : 'blocked'],
    ['Pilot Launch', modelStatus(pilotLaunchReadiness, pilotLaunchReadiness?.privatePilotDecision, 'pilotLaunchDecision')],
    ['Launch Gates', modelRatio(pilotLaunchReadiness, pilotLaunchReadiness?.summary?.passedGateCount, pilotLaunchReadiness?.summary?.gateCount, 'pilotLaunchPassedGateCount', 'pilotLaunchGateCount')],
    ['Launch Routes', modelRatio(pilotLaunchReadiness, pilotLaunchReadiness?.summary?.readyEvidenceRouteCount, pilotLaunchReadiness?.summary?.evidenceRouteCount, 'pilotLaunchReadyEvidenceRouteCount', 'pilotLaunchEvidenceRouteCount')],
    ['Preflight', modelBoolean(deploymentPreflight, deploymentPreflight?.privatePilotDeploymentReady, 'deploymentPreflightReady')],
    ['Preflight Warnings', modelValue(deploymentPreflight, deploymentPreflight?.summary?.failedWarningGateCount, 'deploymentPreflightWarningCount')],
    ['Gateway', modelStatus(adapterGatewayPreflight, adapterGatewayPreflight?.status, 'adapterGatewayPreflightStatus')],
    ['Gateway Live', modelBoolean(adapterGatewayPreflight, adapterGatewayPreflight?.summary?.liveGatewayReady, 'adapterGatewayLiveReady', 'ready', 'pending')],
    ['Gateway State', modelBoolean(adapterGatewayPreflight, adapterGatewayPreflight?.summary?.stateReadable, 'adapterGatewayStateReadable', 'readable', 'pending')],
    [projectText('Infra Rehearsal'), modelStatus(productionInfrastructureRehearsal, productionInfrastructureRehearsal?.status, 'productionInfrastructureRehearsalStatus')],
    [projectText('Infra Ready'), projectText(modelBoolean(productionInfrastructureRehearsal, productionInfrastructureRehearsal?.readyForInfrastructureRehearsal, 'productionInfrastructureRehearsalReady'))],
    [projectText('Infra Blockers'), modelValue(productionInfrastructureRehearsal, productionInfrastructureRehearsal?.summary?.productionBlockedCount, 'productionInfrastructureRehearsalProductionBlockedCount')],
    [projectText('Managed Cutover'), modelRatio(productionInfrastructureRehearsal, productionInfrastructureRehearsal?.managedCutoverSummary?.productionReadyGateCount, productionInfrastructureRehearsal?.managedCutoverSummary?.gateCount, 'productionInfrastructureManagedCutoverReadyCount', 'productionInfrastructureManagedCutoverGateCount')],
    [projectText('Next Cutover'), modelValue(productionInfrastructureRehearsal, productionInfrastructureRehearsal?.managedCutoverSummary?.nextGateId, 'productionInfrastructureManagedCutoverNextGateId')],
    [projectText('Launch Approval'), projectText(modelStatus(launchApprovalWorkflow, launchApprovalWorkflow?.status, 'launchApprovalStatus'))],
    [projectText('Pilot Approval'), projectText(modelBoolean(launchApprovalWorkflow, launchApprovalWorkflow?.readyForPrivatePilot, 'launchApprovalPrivatePilotReady'))],
    [projectText('Production Approval'), projectText(modelBoolean(launchApprovalWorkflow, launchApprovalWorkflow?.readyForProduction, 'launchApprovalProductionReady'))],
    [projectText('Launch Audit'), projectText(modelStatus(productionLaunchAudit, productionLaunchAudit?.status, 'productionLaunchAuditStatus'))],
    [projectText('Private Pilot Audit'), modelStatus(productionLaunchAudit, productionLaunchAudit?.privatePilotDecision, 'productionLaunchPrivatePilotDecision')],
    [projectText('Production Audit'), modelStatus(productionLaunchAudit, productionLaunchAudit?.productionDecision, 'productionLaunchProductionDecision')],
    [projectText('Audit Blockers'), modelValue(productionLaunchAudit, productionLaunchAudit?.summary?.productionBlockerCount, 'productionLaunchProductionBlockerCount')],
    ['Evidence Archive', modelStatus(projectEvidenceArchive, projectEvidenceArchive?.status, 'projectEvidenceArchiveStatus')],
    ['Archive Ready', modelBoolean(projectEvidenceArchive, projectEvidenceArchive?.readyForManagerHandoff, 'projectEvidenceArchiveReady')],
    ['Archive Manifest', modelRatio(projectEvidenceArchive, projectEvidenceArchive?.summary?.readyManifestEntryCount, projectEvidenceArchive?.summary?.manifestEntryCount, 'projectEvidenceArchiveReadyManifestEntryCount', 'projectEvidenceArchiveManifestEntryCount')],
    ['Archive Leaks', modelValue(projectEvidenceArchive, projectEvidenceArchive?.summary?.rawLeakCount, 'projectEvidenceArchiveRawLeakCount')],
    ['Evidence Export', modelStatus(projectEvidenceExportWorkflow, projectEvidenceExportWorkflow?.status, 'projectEvidenceExportStatus')],
    ['Export Ready', modelBoolean(projectEvidenceExportWorkflow, projectEvidenceExportWorkflow?.readyForPrivatePilotHandoff, 'projectEvidenceExportReady')],
    ['Package Ready', modelBoolean(projectEvidenceExportWorkflow, projectEvidenceExportWorkflow?.readyForPrivatePilotDownload, 'projectEvidenceExportDownloadReady', 'ready', 'audit-needed')],
    ['Export Approvals', modelValue(projectEvidenceExportWorkflow, projectEvidenceExportWorkflow?.summary?.approvalCount, 'projectEvidenceExportApprovalCount')],
    ['Go-Live Status', modelStatus(privatePilotGoLiveReadiness, privatePilotGoLiveReadiness?.status, 'privatePilotGoLiveStatus')],
    ['Go-Live Phase', modelValue(privatePilotGoLiveReadiness, privatePilotGoLiveReadiness?.activePhase, 'privatePilotGoLiveActivePhase')],
    ['Go-Live Ready', modelBoolean(privatePilotGoLiveReadiness, privatePilotGoLiveReadiness?.readyForPrivatePilotGoLive, 'privatePilotGoLiveReady')],
    ['Next Go-Live Action', modelValue(privatePilotGoLiveReadiness, privatePilotGoLiveReadiness?.nextAction?.id, 'privatePilotGoLiveNextActionId')],
    ['Release Candidate', modelStatus(privatePilotReleaseCandidateWorkflow, privatePilotReleaseCandidateWorkflow?.status, 'privatePilotReleaseCandidateStatus')],
    ['Candidate Ready', modelBoolean(privatePilotReleaseCandidateWorkflow, privatePilotReleaseCandidateWorkflow?.readyForPrivatePilotRelease, 'privatePilotReleaseCandidateReady', 'ready', 'record')],
    ['Candidate Gates', modelRatio(privatePilotReleaseCandidateWorkflow, privatePilotReleaseCandidateWorkflow?.summary?.passedGateCount, privatePilotReleaseCandidateWorkflow?.summary?.gateCount, 'privatePilotReleaseCandidatePassedGateCount', 'privatePilotReleaseCandidateGateCount')],
    ['Candidate Receipts', modelValue(privatePilotReleaseCandidateWorkflow, privatePilotReleaseCandidateWorkflow?.summary?.candidateCount, 'privatePilotReleaseCandidateCount')],
    ['Pilot Launch Run', modelStatus(privatePilotLaunchRunWorkflow, privatePilotLaunchRunWorkflow?.status, 'privatePilotLaunchRunStatus')],
    ['Launch Run Ready', modelBoolean(privatePilotLaunchRunWorkflow, privatePilotLaunchRunWorkflow?.readyForPrivatePilotLaunch, 'privatePilotLaunchRunReady', 'ready', 'record')],
    ['Launch Run Gates', modelRatio(privatePilotLaunchRunWorkflow, privatePilotLaunchRunWorkflow?.summary?.passedGateCount, privatePilotLaunchRunWorkflow?.summary?.gateCount, 'privatePilotLaunchRunPassedGateCount', 'privatePilotLaunchRunGateCount')],
    ['Launch Run Receipts', modelValue(privatePilotLaunchRunWorkflow, privatePilotLaunchRunWorkflow?.summary?.runCount, 'privatePilotLaunchRunCount')],
    ['Post Launch Health', modelStatus(privatePilotLaunchHealthCheckWorkflow, privatePilotLaunchHealthCheckWorkflow?.status, 'privatePilotLaunchHealthCheckStatus')],
    ['Health Ready', modelBoolean(privatePilotLaunchHealthCheckWorkflow, privatePilotLaunchHealthCheckWorkflow?.readyForPrivatePilotMonitoring, 'privatePilotLaunchHealthCheckReady', 'ready', 'record')],
    ['Health Gates', modelRatio(privatePilotLaunchHealthCheckWorkflow, privatePilotLaunchHealthCheckWorkflow?.summary?.passedGateCount, privatePilotLaunchHealthCheckWorkflow?.summary?.gateCount, 'privatePilotLaunchHealthCheckPassedGateCount', 'privatePilotLaunchHealthCheckGateCount')],
    ['Health Receipts', modelValue(privatePilotLaunchHealthCheckWorkflow, privatePilotLaunchHealthCheckWorkflow?.summary?.healthCheckCount, 'privatePilotLaunchHealthCheckCount')],
    ['Acceptance Report', modelStatus(privatePilotAcceptanceReportWorkflow, privatePilotAcceptanceReportWorkflow?.status, 'privatePilotAcceptanceReportStatus')],
    ['Acceptance Ready', modelBoolean(privatePilotAcceptanceReportWorkflow, privatePilotAcceptanceReportWorkflow?.readyForPrivatePilotAcceptance, 'privatePilotAcceptanceReportReady', 'ready', 'record')],
    ['Acceptance Gates', modelRatio(privatePilotAcceptanceReportWorkflow, privatePilotAcceptanceReportWorkflow?.summary?.passedGateCount, privatePilotAcceptanceReportWorkflow?.summary?.gateCount, 'privatePilotAcceptanceReportPassedGateCount', 'privatePilotAcceptanceReportGateCount')],
    ['Acceptance Reports', modelValue(privatePilotAcceptanceReportWorkflow, privatePilotAcceptanceReportWorkflow?.summary?.reportCount, 'privatePilotAcceptanceReportCount')],
    ['Production Ops', modelStatus(productionOperationsReadiness, productionOperationsReadiness?.status, 'productionOperationsStatus')],
    ['Ops Local Proof', modelBoolean(productionOperationsReadiness, productionOperationsReadiness?.readyForPrivatePilotOperations, 'productionOperationsReadyForPrivatePilot')],
    ['Ops Prod Ready', modelBoolean(productionOperationsReadiness, productionOperationsReadiness?.readyForProductionOperations, 'productionOperationsReadyForProduction')],
    ['Ops Controls', modelRatio(productionOperationsReadiness, productionOperationsReadiness?.summary?.productionControlPassedGateCount, productionOperationsReadiness?.summary?.productionControlGateCount, 'productionOperationsControlPassedGateCount', 'productionOperationsControlGateCount')],
    ['Ops Receipts', modelRatio(productionOperationsControlReceiptWorkflow, productionOperationsControlReceiptWorkflow?.summary?.verifiedControlCount, productionOperationsControlReceiptWorkflow?.summary?.requiredControlCount, 'productionOperationsVerifiedControlCount', 'productionOperationsRequiredControlCount')],
    ['Artifact Audit', modelStatus(artifactQualityAudit, artifactQualityAudit?.status, 'artifactQualityAuditStatus')],
    ['Artifact Ready', modelBoolean(artifactQualityAudit, artifactQualityAudit?.readyForLocalPilot, 'artifactQualityReady', 'ready', 'review')],
    ['Artifact Quality', modelValue(artifactQualityAudit, artifactQualityAudit?.summary?.averageQualityScore, 'artifactQualityAverageScore')],
    ['Artifact Proofs', modelRatio(artifactQualityAudit, artifactQualityAudit?.summary?.proofReadyCount, artifactQualityAudit?.summary?.submissionCount, 'artifactQualityProofReadyCount', 'artifactQualitySubmissionCount')],
    ['Artifact Types', modelRatio(artifactQualityAudit, artifactQualityAudit?.summary?.coveredArtifactTypeCount, artifactQualityAudit?.summary?.requiredArtifactTypeCount, 'artifactQualityCoveredTypeCount', 'artifactQualityRequiredTypeCount')],
    ['Review Workflow', modelStatus(submissionReviewWorkflow, submissionReviewWorkflow?.status, 'submissionReviewWorkflowStatus')],
    ['Review Rounds', modelRatio(submissionReviewWorkflow, submissionReviewWorkflow?.summary?.revisionResponseCount, submissionReviewWorkflow?.summary?.reviewRoundCount, 'submissionReviewRevisionResponseCount', 'submissionReviewRoundCount')],
    ['Delivery Trace', modelStatus(productTeamDeliveryTrace, productTeamDeliveryTrace?.status, 'productTeamDeliveryTraceStatus')],
    ['Trace Ready', modelRatio(productTeamDeliveryTrace, productTeamDeliveryTrace?.summary?.readyCount, productTeamDeliveryTrace?.summary?.rowCount, 'productTeamDeliveryTraceReadyCount', 'productTeamDeliveryTraceRowCount')],
    ['Operating Loop', modelStatus(productTeamOperatingLoop, productTeamOperatingLoop?.status, 'productTeamOperatingLoopStatus')],
    ['Loop Ready', modelBoolean(productTeamOperatingLoop, productTeamOperatingLoop?.readyForLocalPilotOperatingLoop, 'productTeamOperatingLoopReady')],
    ['Loop Next', modelValue(productTeamOperatingLoop, productTeamOperatingLoop?.summary?.nextActionLane, 'productTeamOperatingLoopNextActionLane')],
    ['Handoff Exec', modelStatus(productTeamOperatingLoop, productTeamOperatingLoop?.customerSide?.handoffExecution?.status || productTeamOperatingLoop?.summary?.customerAgentHandoffExecutionStatus, 'customerAgentHandoffExecutionStatus')],
    ['Handoff Runs', modelValue(productTeamOperatingLoop, productTeamOperatingLoop?.customerSide?.handoffExecution?.runReceiptIds?.length ?? productTeamOperatingLoop?.summary?.customerAgentHandoffExecutionRunReceiptCount, 'customerAgentHandoffExecutionRunReceiptCount')],
    ['Handoff Outputs', modelValue(productTeamOperatingLoop, productTeamOperatingLoop?.customerSide?.handoffExecution?.submissionIds?.length ?? productTeamOperatingLoop?.summary?.customerAgentHandoffExecutionSubmissionCount, 'customerAgentHandoffExecutionSubmissionCount')],
    ['Agent Strategy', modelValue(productTeamOperatingLoop, productTeamOperatingLoop?.agentSide?.selectedActions?.length ?? productTeamOperatingLoop?.summary?.selectedAgentActions?.length, 'selectedAgentActionCount')],
    ['Collab Diagnostics', modelStatus(teamCollaborationDiagnostics, teamCollaborationDiagnostics?.status, 'teamCollaborationDiagnosticsStatus')],
    ['Collab Ready', modelBoolean(teamCollaborationDiagnostics, teamCollaborationDiagnostics?.readyForLocalPilotCollaboration, 'teamCollaborationDiagnosticsReady')],
    ['Handoff Breaks', modelValue(teamCollaborationDiagnostics, teamCollaborationDiagnostics?.summary?.failedLocalRowCount, 'teamCollaborationDiagnosticsFailedLocalRowCount')],
    ['Intent Queue', modelStatus(collaborationIntentQueue, collaborationIntentQueue?.status, 'collaborationIntentQueueStatus')],
    ['Intent Ready', modelBoolean(collaborationIntentQueue, collaborationIntentQueue?.readyForLocalPilotIntentQueue, 'collaborationIntentQueueReady')],
    ['Intent Rows', modelRatio(collaborationIntentQueue, collaborationIntentQueue?.summary?.runnableCount, collaborationIntentQueue?.summary?.rowCount, 'collaborationIntentQueueRunnableCount', 'collaborationIntentQueueRowCount')],
    ['Runtime Contracts', modelStatus(runtimeContracts, runtimeContracts?.status, 'runtimeContractsStatus')],
    ['Contracts Ready', modelBoolean(runtimeContracts, runtimeContracts?.readyForLocalPilotContractFreeze, 'runtimeContractsReady')],
    ['Frozen Contracts', modelRatio(runtimeContracts, runtimeContracts?.summary?.frozenLocalContractCount, runtimeContracts?.summary?.localContractCount, 'runtimeContractsFrozenLocalCount', 'runtimeContractsLocalCount')],
    ['Cycle Consistency', modelStatus(autonomousCycleConsistency, autonomousCycleConsistency?.status, 'autonomousCycleConsistencyStatus')],
    ['Cycle Ready', modelBoolean(autonomousCycleConsistency, autonomousCycleConsistency?.readyForLocalPilotCycleConsistency, 'autonomousCycleConsistencyReady')],
    ['Cycle Steps', modelRatio(autonomousCycleConsistency, autonomousCycleConsistency?.summary?.observedStepCount, autonomousCycleConsistency?.summary?.requiredStepCount, 'autonomousCycleConsistencyObservedStepCount', 'autonomousCycleConsistencyRequiredStepCount')],
    ['Runtime Autonomy', modelStatus(runtimeAutonomyStatus, runtimeAutonomyStatus?.status, 'runtimeAutonomyStatus')],
    ['Local Autonomy', modelBoolean(runtimeAutonomyStatus, runtimeAutonomyStatus?.readyForLocalAutonomy, 'runtimeAutonomyReady')],
    ['Production Auto', modelBoolean(runtimeAutonomyStatus, runtimeAutonomyStatus?.readyForUnattendedProduction, 'runtimeAutonomyProductionReady')],
    ['Evidence Audit', modelStatus(evidenceQualityAudit, evidenceQualityAudit?.status, 'evidenceQualityAuditStatus')],
    ['Evidence Ready', modelBoolean(evidenceQualityAudit, evidenceQualityAudit?.readyForDecision, 'evidenceQualityDecisionReady', 'ready', 'review')],
    ['Evidence Quality', modelValue(evidenceQualityAudit, evidenceQualityAudit?.summary?.averageQualityScore, 'evidenceQualityAverageScore')],
    ['Evidence Safety', modelBoolean(evidenceQualityAudit, evidenceQualityAudit?.summary?.sourceSafetyReady, 'evidenceQualitySourceSafetyReady', 'ready', 'review')],
    ['Source Snapshots', modelValue(evidenceQualityAudit, evidenceQualityAudit?.summary?.sourceSnapshotCount, 'evidenceSourceSnapshotCount')],
    ['Provider Receipts', modelValue(evidenceQualityAudit, evidenceQualityAudit?.summary?.providerReceiptCount, 'evidenceProviderReceiptCount')],
    ['Evidence Index', modelStatus(evidenceIndexReadiness, evidenceIndexReadiness?.status, 'evidenceIndexReadinessStatus')],
    ['Index Local', modelBoolean(evidenceIndexReadiness, evidenceIndexReadiness?.readyForLocalMvp, 'evidenceIndexReadinessLocalReady')],
    ['Index Rows', modelRatio(evidenceIndexReadiness, evidenceIndexReadiness?.summary?.evidenceSearchCount, evidenceIndexReadiness?.summary?.submissionCount, 'evidenceIndexReadinessSearchCount', 'evidenceIndexReadinessSubmissionCount')],
    ['Source Review', modelStatus(evidenceSourceReviewWorkflow, evidenceSourceReviewWorkflow?.status, 'evidenceSourceReviewStatus')],
    ['Source Queue', modelValue(evidenceSourceReviewWorkflow, evidenceSourceReviewWorkflow?.summary?.reviewRequiredSourceCount, 'evidenceSourceReviewQueuedCount')],
    ['Source Decisions', modelValue(evidenceSourceReviewWorkflow, evidenceSourceReviewWorkflow?.summary?.sourceReviewDecisionCount, 'evidenceSourceReviewDecisionCount')],
    ['Source Pending', modelValue(evidenceSourceReviewWorkflow, evidenceSourceReviewWorkflow?.summary?.pendingDecisionSourceCount, 'evidenceSourceReviewPendingDecisionCount')],
    ['Evidence Custody', modelStatus(evidenceCustodyReadiness, evidenceCustodyReadiness?.status, 'evidenceCustodyStatus')],
    ['Custody Ready', modelBoolean(evidenceCustodyReadiness, evidenceCustodyReadiness?.readyForPrivatePilot, 'evidenceCustodyReady')],
    ['Custody Records', modelValue(evidenceCustodyReadiness, evidenceCustodyReadiness?.summary?.custodyRecordCount, 'evidenceCustodyRecordCount')],
    ['Custody Storage', modelBoolean(evidenceCustodyReadiness, evidenceCustodyReadiness?.readyForProduction, 'evidenceCustodyProductionReady', 'production-ready', 'managed-blocked')],
    ['Proof Routes', summaryValue('proofRouteCount')],
    ['MVP Core', `${readyPackage.summary?.mvpCorePassedCount ?? mvpReadiness?.summary?.corePassedCount ?? 0}/${readyPackage.summary?.mvpCoreTotalCount ?? mvpReadiness?.summary?.coreTotalCount ?? 0}`],
    ['Prod Blockers', readyPackage.summary?.mvpProductionBlockerCount ?? mvpReadiness?.summary?.productionBlockerCount ?? 0],
    ['Security', modelStatus(securityBoundary, securityBoundary?.status, 'securityBoundaryStatus')],
    ['Providers', modelStatus(providerReadiness, providerReadiness?.status, 'providerReadinessStatus')],
    ['Controlled Run', modelStatus(providerControlledRun, providerControlledRun?.status, 'providerControlledRunStatus')],
    ['Run Ready', modelBoolean(providerControlledRun, providerControlledRun?.readyForPrivatePilotRun, 'providerControlledRunReady')],
    ['Run Ops', modelRatio(providerControlledRun, providerControlledRun?.summary?.runnableOperationCount, providerControlledRun?.summary?.operationCount, 'providerControlledRunRunnableOperationCount', 'providerControlledRunOperationCount')],
    ['Run Cost', modelCents(providerControlledRun, providerControlledRun?.summary?.estimatedRunCostCents, 'providerControlledRunEstimatedCostCents')],
    ['Provider Eval', modelStatus(providerEvalRunWorkflow, providerEvalRunWorkflow?.status, 'providerEvalRunWorkflowStatus')],
    ['Eval Ready', modelBoolean(providerEvalRunWorkflow, providerEvalRunWorkflow?.readyForPrivatePilotProviderEval, 'providerEvalRunReady', 'ready', 'record')],
    ['Eval Runs', modelRatio(providerEvalRunWorkflow, providerEvalRunWorkflow?.summary?.passedRunCount, providerEvalRunWorkflow?.summary?.runCount, 'providerEvalRunPassedCount', 'providerEvalRunCount')],
    ['Eval Critical', modelRatio(providerEvalRunWorkflow, providerEvalRunWorkflow?.summary?.replayedCriticalOperationCount, providerEvalRunWorkflow?.summary?.criticalOperationCount, 'providerEvalRunReplayedCriticalCount', 'providerEvalRunCriticalCount')],
    ['Operations', modelStatus(operationsReadiness, operationsReadiness?.status, 'operationsReadinessStatus')],
    ['Persistence Adapter', summaryStatus('persistenceAdapterDryRunStatus')],
    ['DB Driver', summaryStatus('persistenceAdapterDriver')],
    ['Shadow Reads', summaryValue('persistenceAdapterShadowReadParityCount')],
    ['Adapter Ops', summaryValue('persistenceAdapterOperationCount')],
    ['Queue Adapter', summaryStatus('queueAdapterDryRunStatus')],
    ['Queue Driver', summaryStatus('queueAdapterDriver')],
    ['Queue Dispatches', summaryValue('queueAdapterDispatchCount')],
    ['Queue Leases', summaryValue('queueAdapterLeaseAcquisitionCount')],
    ['Queue Parity', summaryBoolean('queueAdapterSnapshotParityReady')],
    ['Worker Recovery', summaryBoolean('workerRecoveryContractReady')],
    ['Incident Drill', summaryBoolean('operationsIncidentDrillReady')],
    ['Drill Receipts', summaryValue('operationsIncidentDrillReceiptCount')],
    ['Worker Receipts', summaryValue('workerExecutionReceiptCount')],
    ['Dead Letters', summaryValue('workerDeadLetterCount')],
    ['Trail Ready', summaryRatio('scenarioTrailReadyCount', 'scenarioTrailCount')],
    ['Walkthrough', summaryRatio('walkthroughCompletedCount', 'walkthroughCount')],
    ['Requirements', summaryRatio('requirementReadyCount', 'requirementCount')],
    ['Kickoff Board', summaryRatio('kickoffBoardReadyCount', 'kickoffBoardCount')],
    ['Work Loop Board', summaryRatio('workLoopRunningCount', 'workLoopCount')],
    ['Collaboration Board', summaryRatio('collaborationReadyCount', 'collaborationBoardCount')],
    ['Change Protocol', summaryRatio('changeProtocolReadyCount', 'changeProtocolBoardCount')],
    ['Change Owners', summaryRatio('changeOwnerReadyCount', 'changeOwnerCount')],
    ['Use Cases', summaryRatio('useCaseCoveredCount', 'useCaseCount')],
    ['Action Queue', summaryRatio('actionQueueCompletedCount', 'actionQueueCount')],
    ['Unresolved Routes', summaryValue('actionQueueUnresolvedRouteCount')],
    ['Transcript Channels', summaryValue('transcriptChannelCount')],
    ['Ops Agents', summaryValue('operationsAgentCount')],
    ['Assignments', summaryValue('assignmentCount')],
    ['Changes', summaryValue('changeCount')],
  ];

  return (
    <div data-testid="backend-manager-ready-package-summary" className="grid grid-cols-2 md:grid-cols-4 gap-2">
      {rows.map(([label, value]) => (
        <div key={`ready-package-${label}`} className="border border-[#d8c99f] bg-[#efe2bd]/50 px-2 py-1">
          <div className="font-mono text-[7px] uppercase tracking-widest text-[#7d6a49]">{label}</div>
          <div className="font-serif text-base leading-tight">{value}</div>
        </div>
      ))}
    </div>
  );
}
